# -*- coding: utf-8 -*-
"""Deep-dive content for ideas 1-10 (global order). Keys: 'name' must match build_data.py exactly."""

CONTENT_1 = {

"Budget systems, cash-stuffing kits & debt-payoff spreadsheets": dict(
 price_global="$7–$29 digital · $19–$49 binder bundles",
 price_india="₹149–₹499 (sweet spot ₹199–₹299)",
 aov_india="₹250–₹500 · AOV target ₹349",
 aov_global="AOV $19–$35",
 contents=[
  "A 40–60 page 'Paycheck Plan' PDF — monthly budget sheet, bill calendar, sinking-fund tracker, debt snowball page, 50/30/20 planner",
  "Auto-calculating Google Sheets trackers (expense log, savings goals, debt payoff curve, subscription audit)",
  "A6 cash-envelope printables + '₹100 envelope challenge' / 52-week savings challenge cards",
  "UPI-style spending log (India version) — screenshot-and-categorise page for people who don't use cash",
  "30-day savings challenge cards and a fridge-ready monthly review sheet",
  "A 10-minute setup video (screen-recorded) + a filled-in example sheet so buyers don't get stuck",
 ],
 buyers_india="Salaried 24–40 in Tier-1/2 cities who feel broke by the 10th of the month, newly married couples merging finances, students with first jobs, and the '₹10,000 emergency fund' crowd.",
 buyers_global="Women 22–45 living paycheck to paycheck, the cash-stuffing and sinking-funds Reels audience, debt-payoff communities, couples merging finances.",
 why_meta="Payday anxiety is universal and permanent, and the aesthetic (binders, envelopes, challenges, cash counting) is native Reels content. At impulse prices the buyer doesn't deliberate — they buy the feeling of control in one scroll.",
 india_twist="In India the hook changes from 'cash stuffing' (a US aesthetic) to 'salary day system' and 'where did my money go'. Cash is still real in Tier-2/3, so envelope printables work, but the bigger Indian buyer wants a UPI spending log, a SIP/EMI tracker and a monthly review ritual. Free finance content is everywhere in India, so the paid product must be a *system* (sheets + tracker + ritual), not information.",
 proof_global="Pretty Arrow (Emily McDermott) reports 30,000+ shop sales — her first spreadsheet hit $5K/month in 3 months and $15K/month in 6 months, naming Facebook ads as a traffic channel. Top-100 Etsy 'Excel budget template' listings average ~3.0M monthly views at ~$5.36. Cash-stuffing/sinking-funds remains a mainstream finance-media trend through 2026.",
 proof_india="No single documented Indian seller of the same scale — this is the weakest link for India. Evidence is indirect but strong: India's fintech/personal-finance Instagram ecosystem is enormous, budgeting PDFs sell at ₹149–₹499 from creator bios, and Indian digital-product guides list 'spreadsheet/tracker ₹199–₹699' as a standard SKU band. Treat India demand as high and India *proof* as medium.",
 comp_global="High. The category is saturated on Etsy and Pinterest, but volume is so large and evergreen that a well-packaged system still sells.",
 comp_india="Medium-high for free/cheap content, medium for paid systems. Almost nobody in India sells a genuinely good, do-it-with-you bought system at ₹199 — most sellers dump a Canva-looking PDF with no sheets, no video, no support.",
 verify=[
  "Etsy search: 'budget spreadsheet', 'cash stuffing printable' → note listing count and which listings carry 1,000+ reviews",
  "Meta Ad Library, search 'budget planner' + country India → count active advertisers and see how long ads have been running",
  "Instagram search: 'budget planner India', 'salary plan' → check how many accounts post the same offer and what price they show in the caption",
  "Telegram: search 'finance' / 'budget' channels → see whether paid upsells exist inside free channels",
 ],
 score_notes="India score 7.42 (India rank 11, global rank 1 — the single biggest ranking drop in this document). Three factors cause it: price fit 7 (Indians believe money advice should be free, so the paid product has to feel like a tool, not a lecture, and ₹499 is a ceiling here), India proof 6 (no documented Indian seller at scale, only indirect evidence), and competition 6. It scores 10 on payment fit — UPI checkout at ₹199 is frictionless — and the global version stays at #1 because a $9–$29 price with a $19–$37 ladder clears US ad costs, which the Indian price point does not.",
 ladder_india="₹199 'Salary Day Plan' PDF → ₹299 bump: full sheets bundle → ₹699 upsell: '1-year finance vault' (12 monthly updates) → ₹1,499 group workshop or 1:1 review",
 ladder_global="$9 paycheck-plan printable → $19 cash-stuffing binder bump → $37 debt-payoff vault → $9/mo printable club",
 hooks_india=["'Salary aayi aur 7 din mein gayab? Ye system chala ke dekho.'",
              "'Mehine ke pehle din ₹5,000 alag kar lo — bina tension.'",
              "'UPI se paisa udta hai? 30-din ka tracker print karo.'"],
 hooks_global=["'Your paycheck disappears in 3 days. Here's the $9 system that fixed it.'",
               "'Cash stuffing won't work with these 4 envelopes — swap them.'",
               "'Before payday I do these 5 things.'"],
 watch_india="Never sell 'paisa double' or show returns — India has hard rules on financial claims and Meta rejects guaranteed-income creative. Also: WhatsApp file forwarding means your PDF will leak; price for volume, update monthly, and sell the tracker/bundle that can't be forwarded as easily as a single PDF.",
 watch_global="Meta restricts 'personal financial hardship' framing — never say broke, bad with money, or imply you know their financial state. Sell the ritual, not their failure.",
),

"ADHD / neurodivergent planners & life systems": dict(
 price_global="$8–$25 standard · $45–$99 full system",
 price_india="₹199–₹699 (sweet spot ₹299–₹499)",
 aov_india="₹399–₹699",
 aov_global="AOV $25–$45",
 contents=[
  "Undated daily + weekly planner built for low stimulus (few boxes, no colour noise, no 'perfect life' prompts)",
  "Brain-dump sheets, a task-sorter ('3 things today'), and a done-list instead of a to-do list",
  "A 10-minute body-doubling audio track and a 'dopamine menu' poster to break task paralysis",
  "Executive-function workbook pages: starting tasks, time-blindness clocks, transition warnings, money/ADHD friction",
  "Study-mode timetable for students (exam weeks, revision blocks) and a phone-boundary sheet",
  "Printable + tablet (GoodNotes) versions, plus a Notion duplicate link",
 ],
 buyers_india="Students in Class 9–12 and college who 'sit down to study and end up on the phone', metro 20–35s who relate to ADHD/attention content, and parents looking for structure for a distracted child.",
 buyers_global="Adults with late-diagnosed ADHD, students, parents of ADHD kids, women 20–40 who have tried every planner.",
 why_meta="Identity-driven purchase with a ready-made emotional failure story ('normal planners don't work for me'), cheap to build in Canva, and the creative writes itself: low-stimulus page flips, brain-dump demos, 'planner on a bad brain day'.",
 india_twist="India's market is smaller on the *diagnosis* identity and bigger on the *student focus* problem. Sell it as a focus/exam system for distracted students and busy young professionals — that audience is 20× bigger than the diagnosed-ADHD audience in India, and it is culturally acceptable to buy (nobody wants to admit a diagnosis in a family WhatsApp group).",
 proof_global="A single ADHD digital planner reports 50,000+ sales on Etsy. On Gumroad, a top ADHD planner shows 3,100+ sales at $17 (~$52K) plus a $99 version with 225 sales (~$22K). Multiple 2026 trend tools list ADHD tools as a rising Etsy category, with simpler layouts beating busy ones.",
 proof_india="Medium. Indian 'study with me', 'topper timetable' and focus content performs strongly, and planners sell from creator bios at ₹199–₹599, but there is no well-documented Indian ADHD-planner bestseller. The India play leans on the student-focus framing, where the paying market is proven (coaching, timetables, study kits).",
 comp_global="High and rising. The low-stimulus aesthetic is being copied fast; differentiators are the workbook depth and the body-doubling/audio layer, which copycats don't bother making.",
 comp_india="Medium. Basic 'timetable PDFs' are given away free by coaching institutes, but a genuinely designed focus system with audio and a workbook is rare in Hindi/Hinglish.",
 verify=[
  "Etsy search 'ADHD planner' → note how many listings carry 1,000+ reviews and what price they hold",
  "Gumroad Discover → search 'ADHD' → check sales counters on top products",
  "Instagram (India) search 'focus planner', 'study timetable' → see what Indian accounts charge and how they present it",
  "Meta Ad Library (India) → search 'focus planner' / 'study planner' and count active creatives",
 ],
 score_notes="India score 7.01 (India rank 13 vs global rank 2 — the second-biggest drop). India demand is 6 and India proof 5 because the *diagnosed* ADHD identity market is small here; the paying market is the much bigger 'distracted student / focus' audience, which is why the India ladder is priced and framed around study. Competition is soft (8) and price fit moderate (7), but ladder depth 7 and policy 8 (mental-health adjacency) keep it out of the India top ten.",
 ladder_india="₹299 focus planner → ₹399 bump: + body-doubling audio & wallpaper pack → ₹799 upsell: 'Exam Mode' system (timetables, revision tracker, parent sheet) → ₹1,499 study-cohort or 1:1 planning call",
 ladder_global="$12 low-stimulus planner → $19 executive-function workbook bump → $49 bundle + audio → $12/mo accountability club",
 hooks_india=["'Padhne baithte ho aur 5 minute mein phone? Ye planner uske liye hai.'",
              "'Topper ka timetable copy mat karo — apna banao.'",
              "'Distraction ka ilaaj discipline nahi, system hai.'"],
 hooks_global=["'If to-do lists have never worked for you, you don't need more discipline.'",
               "'This is what my planner looks like on a bad brain day.'",
               "'3 planner features that actively make ADHD worse.'"],
 watch_india="Do not sell this as a medical or mental-health product in India — no 'ADHD cure', no diagnosis claims, no doctor-style language. Keep 18+ targeting if the creative mentions ADHD. Also, exam-season seasonality is real (Jan–Mar peaks).",
 watch_global="Mental-health adjacency: sell tools and structure, never treatment, cure or symptom claims.",
),

"Wedding & event template suites (Canva/editable)": dict(
 price_global="$12–$50 per suite",
 price_india="₹399–₹2,999 (sweet spot ₹499–₹999)",
 aov_india="₹999–₹2,499 · AOV target ₹1,299",
 aov_global="AOV $35–$80",
 contents=[
  "8–12 editable invitation suites covering the styles Indian families actually ask for (royal traditional, minimal modern, pastel floral, South Indian, Sikh, Muslim) plus English + Hindi text versions",
  "Digital invite VIDEO templates (CapCut/Canva project files) — the format Indian couples now send on WhatsApp",
  "Mehendi / haldi / sangeet decor printables: welcome boards, signage, favour tags, table numbers, photo-booth props",
  "Ceremony kit: seating chart, menu cards with veg/non-veg marks, baraat & vidai timeline, ritual-day checklist",
  "Bride-side and groom-side checklists plus an Indian wedding budget tracker (in ₹, with vendor tabs: caterer, decor, photographer, pandit)",
  "Hashtag generator sheet, thank-you cards, and a 30-page 'last 30 days' planning checklist",
 ],
 buyers_india="Newly engaged couples 24–35 (metro + Tier-2), their siblings/cousins who plan the wedding, wedding planners and decorators buying templates for client work, and families planning a ₹5–₹50 lakh wedding who still won't pay a designer.",
 buyers_global="Newly engaged couples (especially 'wedding on a budget'), bridesmaids, mothers-of-the-bride — and vendors who resell.",
 why_meta="The moment someone is engaged, every scroll becomes a purchase decision; Meta is excellent at finding that behaviour. The price is anchored against a ₹15,000–₹1,50,000 designer bill, delivery is instant, and Indian wedding content is one of the highest-engagement formats on Indian Instagram.",
 india_twist="This is the rare category where India is *better* than the West: more weddings, bigger spend, bigger emotional stakes, higher engagement, and the digital-invite-video format (WhatsApp-forwardable) has no direct Western equivalent. Indian buyers pay ₹499–₹2,999 happily and buy multiple products across the wedding. Pure Etsy-style minimalism doesn't sell here — you need traditional, regional and video formats.",
 proof_global="Wedding printables show ~1.16M monthly views on top Etsy listings at an average $15.83, with individual invitation templates reporting 13,000+ purchases; wedding stationery is consistently a top-5 Etsy digital category, and editable Canva templates command a 20–40% price premium.",
 proof_india="Strong, though mostly evidenced through the creator economy rather than marketplace counters: Indian digital-invite and wedding-template sellers run profitable Instagram shops at ₹299–₹2,999, vendors buy templates for clients, and Indian creator guides list 'Canva templates ₹299–₹999 / wedding invites' as a top-selling SKU. Season (Nov–Feb and Apr–Jun) drives most sales.",
 comp_global="High, but the ceiling is high too. Design sameness is the real competitor.",
 comp_india="Medium-high for basic invites, genuinely low for regional/ritual-specific packs (Jain, Marwari, Gujarati, Tamil, Telugu, Bengali traditions) and for video invites. That's where a small seller can own a niche.",
 verify=[
  "Meta Ad Library (India) → search 'wedding invitation', 'digital invite' → count active advertisers and how long they've been running (long-running = profitable)",
  "Instagram: search 'digital wedding invite India' → note the price each seller shows in bio/comment (₹299, ₹499, ₹999, ₹2,499) and DM volume in comments",
  "Etsy: search 'wedding invitation template' → evidence for global demand and pricing",
  "Ask 3 local wedding decorators whether they buy templates — that's your B2B channel",
 ],
 score_notes="India score 9.14 — top of the list, and the only idea that maxes demand (10), price fit (10) and Instagram fit (10) at the same time. Payment fit is 10 because a ₹499 UPI checkout is frictionless for a family already spending lakhs on the wedding. India proof is 8 rather than 10: the evidence is strong but comes from creator-economy selling behaviour rather than marketplace counters. Competition (6) is the only real drag — and the open lane is regional/ritual-specific packs, not another generic invite.",
 ladder_india="₹499 single invite suite (printable) → ₹999 bump: + editable video invite + signage pack → ₹2,499 upsell: full wedding kit (invites, decor, timelines, budget tracker) → ₹4,999 wedding-planner bundle / B2B licence for decorators",
 ladder_global="$19 invitation suite → $29 day-of + signage bump → $69 full stationery bundle → $149 wedding ops kit",
 hooks_india=["'Shaadi ka invitation ₹49,000 ka? Ye wala ₹499.'",
              "'Baraat se vidaai tak — poora wedding kit.'",
              "'Mehendi decor 20 minute mein print karo.'"],
 hooks_global=["'We printed our whole wedding for £40.'",
               "'The 6 printables that stop the panic in the last 2 weeks.'",
               "'POV: your seating chart changes again.'"],
 watch_india="Two India traps: (1) buyers often don't know Canva — include a setup video or the refund rate eats you; (2) regional correctness matters (spelling, ritual order, community-specific customs) and getting it wrong gets you savaged in comments. Also expect a hard seasonal curve: Nov–Feb and Apr–Jun peak, monsoon and Shraddha period dip.",
 watch_global="No policy landmine. Win on art direction, not another minimal serif suite.",
),

"Kids' educational printables, homeschool & screen-free activity bundles": dict(
 price_global="$4–$14 single packs · $19–$39 bundles",
 price_india="₹149–₹999 (sweet spot ₹249–₹499)",
 aov_india="₹499–₹1,499 (annual memberships work)",
 aov_global="AOV $22–$40 + recurring",
 contents=[
  "Class-wise worksheet packs aligned to CBSE/ICSE and state boards (LKG–Class 5): maths, English, EVS, Hindi vyakaran, GK",
  "Phonics and early-reading set (CVC words, blending, sight words) with flashcards",
  "Handwriting and motor-skill practice sheets (patterns, cursive, tracing) that parents can print repeatedly",
  "Nursery/admission prep kit: 30-day plan, interview questions, pattern and colour learning",
  "Holiday and screen-free activity bundles: travel packs, rainy-day kits, festival activity packs (Diwali, Raksha Bandhan, Holi)",
  "A parent tracker (weekly progress sheet) + answer keys, so a parent can run it without a teacher",
 ],
 buyers_india="Parents of 3–11 year olds in Tier-1/2/3 cities, especially mothers in WhatsApp school groups; tuition teachers and small coaching centres who need class material; homeschool families.",
 buyers_global="Parents of 3–11s, homeschool families, teachers, grandparents, babysitters.",
 why_meta="Parents buy repeatedly across the full year, the product is a weekend of Canva work, and a printable membership converts one-off buyers into recurring revenue. Parenting content is one of the highest-engagement verticals on Indian Instagram.",
 india_twist="India is one of the best markets in the world for this: intense academic anxiety, large young population, print-happy households, and WhatsApp groups that spread products for free (good for reach, bad for pricing). The winning angle is not 'fun worksheets' — it is 'no more phone', 'admission prep' and 'holiday homework'. Price per class-level pack, then sell the year bundle.",
 proof_global="Curriculum-aligned worksheet bundles, party kits and holiday kits are named as the reliable sellers in printables, with buyers purchasing repeatedly across the year. The category's own analysts note single items don't survive ad costs and bundles are essential.",
 proof_india="Strong market evidence: Indian parents pay for printable worksheets and holiday homework packs at ₹149–₹499; teachers and coaching centres buy class material; activity/worksheet packs are listed as a standard Indian digital-product SKU. Documented Indian seller earnings in this niche typically show up as creator income (₹10k–₹50k+/month) rather than marketplace counters.",
 comp_global="Medium-high. New sellers constantly appear, but demand is segmented by age and subject so a specific grade/subject still has room.",
 comp_india="High on free content (teachers share PDFs on Telegram and WhatsApp), medium on paid, low on *branded* class-wise systems with answer keys and a parent tracker. Differentiation = alignment + language + organisation.",
 verify=[
  "Instagram: search 'worksheets for kids India', 'CBSE worksheets' → see prices in bios and how many accounts sell the same thing",
  "Telegram: check whether free teacher-share channels exist (they do) — measure quality, not quantity",
  "Meta Ad Library (India): search 'worksheets', 'kids activity' → count active ads and how long-running they are",
  "Ask your local school WhatsApp group what they already pay for",
 ],
 score_notes="India 8.70 — third overall. Demand 9.5 (every parent, every year), price fit 9, payment fit 10, policy safety 10 (no claims, no regulation). Competition 6 and IG fit 8 are the only dents: the ad creative is harder (you must make worksheets look fun in 8 seconds).",
 ladder_india="₹249 per class-level pack → ₹499 bump: term bundle → ₹999 upsell: full-year pack (all subjects) → ₹1,499/yr membership with monthly fresh sheets",
 ladder_global="$9 themed activity pack → $19 term-1 survival pack bump → $27 mega bundle → $9/mo printable club",
 hooks_india=["'Bacche ko phone se hatana hai? Ye print karo.'",
              "'Nursery admission ke liye 30-din ka ready plan.'",
              "'Har class ke liye CBSE-aligned worksheets — print, karo, done.'"],
 hooks_global=["'The 20 minutes before dinner that used to be a meltdown.'",
               "'Print this before your next flight.'",
               "'Summer slide is real — 10 pages a week beats tutoring.'"],
 watch_india="Free-file leakage is the biggest risk: one buyer can forward a 500-page pack to 20 parents. Never sell one giant PDF — sell class-wise packs, add a parent tracker and monthly updates, and use a delivery link that changes. Also keep the workload honest: parents refund fast if the sheets are AI-garbled or badly printed at A4.",
 watch_global="Heavy seasonality (back-to-school, summer, Christmas). Build a themed drop calendar or revenue swings 3–4×.",
),

"Canva template packs for small businesses & social media kits": dict(
 price_global="$9–$49 per pack · $25–$79 brand kits",
 price_india="₹299–₹1,999 (sweet spot ₹499–₹999)",
 aov_india="₹999–₹1,999",
 aov_global="AOV $30–$60",
 contents=[
  "50–100 Instagram post templates + 30 story templates, sized and tested on mobile",
  "Festival and occasion packs (Diwali, Raksha Bandhan, Navratri, Independence Day, sale/coupon days) — the single most-bought Indian add-on",
  "Reel cover templates, WhatsApp status templates, and offer/festival banners",
  "Business basics: price list, menu card, visiting card, offer flyer, WhatsApp catalogue images",
  "Hinglish caption bank (50 hooks + CTAs) so the buyer doesn't need a copywriter either",
  "A 'post this in 10 minutes' workflow video + brand-colour edit instructions",
 ],
 buyers_india="Local businesses — boutiques, salons, cafes, gyms, coaching institutes, real-estate agents, jewellers, cloud kitchens, D2C resellers — and the freelancers who serve them. Most have an Instagram account but no designer and no content plan.",
 buyers_global="Etsy/Shopify sellers, coaches, realtors, restaurants, freelancers, podcasters — anyone with a budget and a deadline.",
 why_meta="The product IS the ad creative, so one Reel demos everything in 8 seconds. B2B buyers pay more willingly at the same price point, and kits stack naturally into bundles, memberships and services.",
 india_twist="India has an enormous 'small business on Instagram' population, and template packs sell here at ₹299–₹999 with festival packs as the highest-converting add-on. Competition is very high on generic 'Instagram templates', so the money is in *niche* packs (boutique, cafe, salon, coaching institute) and in being the seller who also offers ₹4,999/month done-for-you as an upsell. This is also the most natural on-ramp to a service business in India.",
 proof_global="Named the fastest-growing digital product segment in 2026 trend analysis; a single 'neutral Instagram post templates' pack is documented at 20,000+ sales; top-100 Etsy social/business template listings sit in a $5–$49 band at 85–95% margins. Niche kits (dog trainers, podcasters, restaurants) flagged high-demand / low-competition.",
 proof_india="Strong. Indian creator-market analysis puts Canva template packs at ₹299–₹999 with top sellers earning ₹50,000+/month, and Indian guides list 'Canva templates for small businesses, festival-themed, Hindi/English mix' as one of the top-selling digital product types in India. The service upsell (₹2,000–₹7,000/month per client) is well documented.",
 comp_global="High. Winning on niche + polish + packaging, not on template count.",
 comp_india="Very high on generic packs (everyone sells '100 Instagram templates' for ₹199). Low-to-medium in vertical niches and in regional language (Marathi/Tamil/Telugu/Gujarati captions + templates), which almost nobody serves.",
 verify=[
  "Instagram India: search 'canva templates for business' → count sellers, note prices and whether any has a niche",
  "Meta Ad Library (India): search 'instagram templates' → long-running ads signal a working offer",
  "Check 10 local businesses nearby — how many post inconsistently? That's your market size",
  "Look at what Indian digital-product course sellers teach as the 'best starter product' (this is always #1)",
 ],
 score_notes="India 8.99 — second overall. Demand 9.5 (lakhs of small businesses), price fit 9, IG fit 9, proof 9 (well-documented Indian earnings), ladder 9 (services upsell). Only competition (6) and the need for real design skill pull it back.",
 ladder_india="₹499 niche pack → ₹999 bump: + festival pack + caption bank → ₹1,999 upsell: brand kit (logo, colours, fonts, 200 templates) → ₹4,999+/mo done-for-you social retainer",
 ladder_global="$19 niche template pack → $29 content calendar + captions bump → $59 brand kit → $19/mo template club",
 hooks_india=["'Aapke post dekhke customer nahi aata? Content ka problem hai, product ka nahi.'",
              "'Diwali ke 30 posts, ready-made — ₹499.'",
              "'Boutique owners: poora month ka content ek pack mein.'"],
 hooks_global=["'Your feed is costing you clients — same offer, 4 different faces.'",
               "'Swipe 20 templates that already converted for a [niche] business.'",
               "'I built this whole week of content in 4 minutes.'"],
 watch_india="Two India-specific traps: (1) buyers often need help editing — if you don't give a 10-minute tutorial, refunds spike; (2) resale piracy is rampant, so price at ₹499 and rely on volume plus the service upsell instead of guarding the file. Never use Canva/Instagram logos in ad creative, and never put ©-ed photos or fonts inside paid packs.",
 watch_global="Never imply platform affiliation, and never ship ©-ed assets — buyers get takedowns and you get refunds.",
),

"Nursing / medical-student study bundles": dict(
 price_global="$3–$25 per bundle",
 price_india="₹99–₹999 (sweet spot ₹199–₹499)",
 aov_india="₹499–₹999",
 aov_global="AOV $20–$35",
 contents=[
  "Illustrated anatomy & physiology notes (all body systems) with mnemonics",
  "Pharmacology drug charts — classification, mechanism, side effects, nursing considerations",
  "Clinical sheets: lab values, normal ranges, procedures, instruments, drug calculations",
  "Exam packs for the exams Indian nurses actually sit: NORCET, ESIC, state staff-nurse, GNM/BSc Nursing university papers",
  "Previous-year questions + solutions, and rapid-revision one-liners for the last 15 days",
  "Flashcards (printable) and a Hindi + English version of every core sheet",
 ],
 buyers_india="GNM/BSc Nursing students and staff-nurse exam candidates (millions across India), ANM students, paramedical and pharmacy students, and working nurses preparing for promotions.",
 buyers_global="Nursing students, NCLEX/pre-nursing candidates, med and allied-health students, paramedics.",
 why_meta="Urgent pain (an exam they have paid heavily to sit), repeat purchase every semester/attempt, and a native format — aesthetic study notes and 'study with me' reels are already a huge Instagram genre.",
 india_twist="India is a bigger nursing market than the West by volume, but the culture is free-PDF-on-Telegram. What people still pay for: exam-specific packs (NORCET/staff nurse), Hindi medium explanations, printed-ready one-liners, and mock tests. Regional and Hindi content is under-served; English-only sellers fight over the same metro students.",
 proof_global="Nursing/anatomy listings on Etsy routinely carry 500–2,000 reviews with 'high sales volume over the past 6 months' flags, priced $2.88–$25, including mega bundles of 350–1,000+ pages; a single nursing concept-map template shows 2,000 reviews.",
 proof_india="Medium-strong. India's exam-prep publishing market (Testbook, Adda247 and similar) proves mass willingness to pay for exam content; individual sellers push nursing notes via Instagram/Telegram at ₹99–₹499. No single Indian nursing-notes seller is publicly documented, so treat this as 'proven category, unproven individual benchmarks'.",
 comp_global="High but segmented by exam and subject.",
 comp_india="Very high on free content; medium on quality exam-specific paid packs; low on Hindi-language and state-exam-specific nursing material.",
 verify=[
  "Telegram: count nursing-exam channels and their subscriber numbers, then look for paid channels inside them",
  "Instagram India: search 'norcet notes', 'nursing notes' → note prices and how sellers package (PDF vs printed)",
  "Check what Testbook/Adda247 charge for the same exam → that's your pricing ceiling",
  "Etsy: search 'nursing notes' → global evidence and price bands",
 ],
 score_notes="India 8.09. Demand 9 (enormous, annual, urgent), price fit 8, payment fit 10, policy safety 9 (pure education). Competition 6 and IG fit 7 (harder to make notes look exciting in 8 seconds — use exam-fear hooks and 'study with me' visuals).",
 ladder_india="₹199 one-subject pack → ₹499 bump: 3-subject bundle → ₹999 upsell: full syllabus + mock tests → ₹1,499 yearly (updated PYQs + monthly current affairs)",
 ladder_global="$7 subject cheat sheet → $12 subject bundle bump → $29 full-semester bundle → $59 across-semester vault",
 hooks_india=["'NORCET ke liye sirf ye 40 pages kaafi hain.'",
              "'Hindi mein anatomy — finally samajh aayega.'",
              "'Last 15 din ka revision plan, print-ready.'"],
 hooks_global=["'I failed A&P the first time. These 12 pages are what I'd do differently.'",
               "'Your lecturer won't tell you which 40 facts show up every exam.'",
               "'Study with me: full bundle, page by page.'"],
 watch_india="Copyright is the real danger: republishing coaching PDFs, NCERT content or paid test series material gets you banned and sued. Write original notes, cite sources, get a senior nurse/lecturer to verify accuracy, and never imply endorsement by an exam body (NORCET/ESIC). Also, buyers share files on Telegram — sell updated editions and mock tests instead of static PDFs.",
 watch_global="Accuracy is the product. Never imply endorsement by an exam body.",
),

"Digital iPad / GoodNotes planners & hyperlinked systems": dict(
 price_global="$6–$25 · $29–$49 deluxe",
 price_india="₹299–₹899 (small market — iPad penetration limits it)",
 aov_india="₹499–₹999",
 aov_global="AOV $25–$45",
 contents=[
  "Hyperlinked PDF planner (yearly + monthly + weekly + daily) built for GoodNotes, Notability and Android note apps",
  "Dashboards: goals, habits, finances, study tracker, project pages with tabs and clickable navigation",
  "Sticker packs (PNG) and cover page sets in 5 aesthetics",
  "Blank + dated versions so the buyer can start mid-year",
  "A starter guide video (how to import, how to write, how to duplicate pages)",
  "Bonus: a 'paper-like' template set for note-taking and lecture capture",
 ],
 buyers_india="Metro students, designers and creators with iPads + Apple Pencil (a small but growing segment), digital artists, and people who bought a tablet for notes and use it for nothing.",
 buyers_global="iPad-only students and 20–35s, aesthetic note-taking creators, people who bought an Apple Pencil and use it for nothing else.",
 why_meta="The purchase is peer-visible, flip-through Reels are native IG content, and the format supports endless variants — dated/undated, themed, per-profession — so creative never goes stale.",
 india_twist="India's iPad base is smaller and concentrated in metros, so this is a *foreign-first* product for an Indian seller: sell it in USD/EUR on Gumroad and Etsy, and treat India as a side market. If you do sell locally, sell the aesthetic and the tutorial, and price at ₹299–₹599.",
 proof_global="Etsy listing evidence: GoodNotes reading journal at 12.4k sales, an iPad reading planner at 4.3k sales, a dark-mode planner at 3.6k sales; digital planners rank top-3 across Etsy digital categories at $8–$25 with ~95% margins.",
 proof_india="Weak. The buyer base exists but is thin, and Indian buyers more often use free Notion/Google Calendar. This is the clearest example of an idea to run *for* the US/EU, not India.",
 comp_global="High. Differentiate with a specific profession or aesthetic, not another undated planner.",
 comp_india="Low-moderate, but so is demand — a thin market is not the same as an open market.",
 verify=[
  "Etsy: 'digital planner GoodNotes' → sales counters on top listings (global demand proof)",
  "Instagram India: search 'digital planner' → how many Indian creators sell it and what they charge",
  "Check Gumroad Discover for how crowded the GoodNotes category is",
 ],
 score_notes="India 6.42 (rank 18). India demand 5, proof 4 — the honest read is that Apple Pencil penetration in India doesn't yet support this as a primary market. It stays in the list because it's a strong *export* product (US/EU customers, paid in USD).",
 ladder_india="₹399 starter planner → ₹599 bump: + sticker pack → ₹999 bundle (dated + undated + 5 themes) → ₹1,499/yr updated edition",
 ladder_global="$12 starter planner → $19 sticker/dashboard bump → $39 all-in bundle → $15/yr updated edition",
 hooks_india=["'Poora 2026 ek PDF mein — iPad wale dekho.'",
              "'Planner ₹12 ka, replacement ₹5,000 ka.'"],
 hooks_global=["'My whole 2026 fits in one file.'",
               "'Why my planner costs $12 and replaced a $60 one.'",
               "'Undated vs dated — here's which one you actually want.'"],
 watch_india="Don't spend Indian ad money here. If you build it, list it on Etsy/Gumroad in USD and run Meta ads to the US/UK/AU. Also state app compatibility clearly or you'll drown in support DMs.",
 watch_global="Device fragmentation kills conversion: state hyperlinked-PDF + GoodNotes/Notability/Android compatibility explicitly.",
),

"Reading journals, book trackers & bookish products": dict(
 price_global="$3–$15 · $12–$25 deluxe",
 price_india="₹149–₹399 (small market)",
 aov_india="₹299–₹599",
 aov_global="AOV $15–$28",
 contents=[
  "Printable reading journal (60–120 pages): TBR lists, book review pages, star ratings, monthly wrap-ups, reading challenge grids",
  "2026 dated tracker + an undated version for mid-year buyers",
  "Digital GoodNotes version with hyperlinked tabs and stickers",
  "Bookish extras: quote pages, book-club discussion sheets, 'books I own vs borrowed' shelf tracker",
 ],
 buyers_india="English-reading 18–30s in metros, Bookstagram/BookTube India, book clubs (small but real), and readers who want to track a yearly challenge.",
 buyers_global="BookTok/Bookstagram readers 18–35, book-club members, romance/romantasy identity buyers.",
 why_meta="The cheapest product on this list to make and among the easiest to advertise — the audience self-identifies loudly, the product is aesthetic by nature, and it re-purchases every January.",
 india_twist="India's paying bookish market is much thinner than the West's: the audience reads, but journaling/tracking culture and impulse spend on stationery PDFs are smaller, and ₹149 is a psychological ceiling for a file. This is an export product. Note the annual re-purchase moment (December–January) makes it an excellent seasonal drop.",
 proof_global="Bookish products described as 'booming thanks to BookTok'; Etsy digital reading journals show 3.6k–12.4k sales, printable reading bundles 12.3k sales, single trackers 1.8k–3.9k reviews, dedicated 2026 trackers at $2.20–$15.",
 proof_india="Weak-to-medium. Indian Bookstagram is growing fast but paid-tracker sales evidence is thin; most Indian bookish sellers monetise through affiliate links and brand deals rather than PDFs.",
 comp_global="Medium-high, with an annual January surge.",
 comp_india="Low competition precisely because demand is thin.",
 verify=[
  "Etsy: 'reading journal', 'book tracker' → check sales counters (this is where the money is)",
  "Instagram India: search '#bookstagramindia' → see whether anyone sells a tracker",
  "Check Etsy's January spike: search '2026 reading tracker' and look at listing dates",
 ],
 score_notes="India 6.25 (rank 19). India demand 3.5→5 and proof 4: the audience is real but the buyer isn't. Foreign demand is genuine and cheap to serve, so it earns its place as an export idea with a January spike.",
 ladder_india="₹149 printable tracker → ₹299 bump: review pack + stickers → ₹599 bundle (printable + GoodNotes + 2027 edition)",
 ladder_global="$5 printable tracker → $9 review + TBR pack bump → $19 digital journal → $29 yearly edition",
 hooks_india=["'Saal mein kitni kitaabein padhi? Ye tracker bata dega.'",
              "'Book club ke liye review pages, ready.'"],
 hooks_global=["'I read 61 books last year. This is the only tracker I used.'",
               "'Book tracking but it's an iPad journal.'",
               "'Fill a shelf without buying anything new.'"],
 watch_india="A ₹149 file cannot carry paid traffic — run this organically (Bookstagram) or as a bundle/add-on, or sell it to a foreign audience at $9–$15 where the maths works.",
 watch_global="Always bundle; never run the single cheap file as the stand-alone offer.",
),

"AI prompt packs & 'AI for [profession]' playbooks": dict(
 price_global="$9–$29",
 price_india="₹149–₹599 (sweet spot ₹299)",
 aov_india="₹499–₹999",
 aov_global="AOV $25–$50",
 contents=[
  "300–500 tested prompts organised by job-to-be-done (not by 'category'), written for a specific profession",
  "Fill-in-the-blank prompt frameworks so output stays consistent across uses",
  "Before/after examples: the weak prompt, the strong prompt, the actual output",
  "Workflow sheets: how to chain prompts into one deliverable (a week of content, a lesson plan, a client proposal, a resume)",
  "Hinglish + English versions for India (and other-language versions for export)",
  "A short video walkthrough showing the three prompts that matter most, plus monthly updates",
 ],
 buyers_india="Students and job-seekers, teachers and tuition owners, real-estate agents, doctors/clinic staff, small-business owners, freelancers and content creators — anyone who has tried ChatGPT, got a mediocre answer and blamed themselves.",
 buyers_global="Solopreneurs, realtors, teachers, marketers, recruiters, students.",
 why_meta="The cheapest product to make and the most demoable ad on the internet: screen-record the prompt, screen-record the output. Curiosity is the cheapest conversion trigger on Meta, and buyer inflow is still growing rather than cannibalising.",
 india_twist="India is arguably the strongest market for this: huge young population, high AI curiosity, English proficiency, and Reels virality around 'AI se kaam karo'. But it's also the fastest-copying niche in the country — generic '500 ChatGPT prompts' packs sell for ₹99 and are given away free. Money is in *profession-specific* packs with tested outputs and a Hindi/Hinglish walkthrough, sold to people who earn money with the output (realtors, teachers, clinic staff, freelancers).",
 proof_global="AI productivity workflows tracked at roughly +180% YoY, with role-specific automation guides up ~210% and marked low-competition; prompt packs are named a top trending digital type across Gumroad, Etsy and Whop at $9–$19.",
 proof_india="Medium-strong. Indian creator-market guides list prompt packs at ₹149–₹499 as a standard SKU, and Indian AI-content creators sell these heavily on Instagram. Individual earnings are not publicly documented, and the market is being flooded right now, so speed and niche matter more than polish.",
 comp_global="Very high and worsening fast.",
 comp_india="Very high on generic packs; low on profession-specific packs in Hindi/Hinglish with real output proof.",
 verify=[
  "Meta Ad Library (India): search 'AI prompts', 'ChatGPT prompts' → count active advertisers; if 50+ are running, the niche is crowded but proven",
  "Instagram: search 'AI prompts India' → note price points and how saturated the creative looks",
  "Check Gumroad/Etsy for generic prompt packs → confirms the commodity price floor",
 ],
 score_notes="India 7.72 (rank 9). Demand 9 and IG fit 9 are excellent; competition 4 and India proof 6 drag it down — the market is real but you're entering a gold rush where the shovels are free. Only enter with a named profession and a demo you can show on screen.",
 ladder_india="₹299 profession pack → ₹599 bump: + workflow videos + templates → ₹1,299 upsell: vault + monthly updates → ₹2,999 mini-course or workshop",
 ladder_global="$9 profession pack → $19 workflow + templates bump → $39 450-prompt vault → $19/mo updated prompt club",
 hooks_india=["'Realtor ho? Ye 12 prompts aapka Sunday bacha denge.'",
               "'Hindi mein 200 tested ChatGPT prompts.'",
               "'Poore mahine ka content, 20 minute mein — AI se.'"],
 hooks_global=["'This one prompt replaced my $400/mo copywriter.'",
               "'Stop asking ChatGPT to \"write a post\". Do this instead.'",
               "'Every realtor should have these 12 prompts saved.'"],
 watch_india="Never sell 'AI se paise kamao' — income claims get rejected and Indian buyers are already sceptical of AI-money pitches. Show real outputs, name the profession in the hook, and update monthly or the $99 copycats will outrank you within weeks.",
 watch_global="The highest-risk ad copy you can write is a make-money-with-AI claim. Win only with a painful niche and a real workflow.",
),

"Resume / LinkedIn / job-search kits (ATS-ready)": dict(
 price_global="$8–$20 single · $15–$30 bundles",
 price_india="₹199–₹999 (sweet spot ₹299–₹499)",
 aov_india="₹499–₹1,499",
 aov_global="AOV $25–$60",
 contents=[
  "10 ATS-safe resume templates in Word, Google Docs and Canva (fresher + experienced variants)",
  "Naukri and LinkedIn optimisation checklists: headline, about, keywords, open-to-work, recruiter-search basics",
  "Hinglish cover-letter and cold-DM templates (email, LinkedIn, referral request)",
  "Interview question bank with model answers (HR + technical-round basics) for the specific role",
  "Salary-negotiation script and a 'why should we hire you' framework",
  "A 7-day job-search plan so the buyer acts instead of just downloading",
 ],
 buyers_india="Freshers from Tier-2/3 colleges, IT/BPO/QA/sales job-seekers, people laid off or returning after a break, and career-switchers into data/analytics/cloud.",
 buyers_global="Job seekers in a panic — recent grads, laid-off mid-career professionals, career-changers, people re-entering after a break.",
 why_meta="Urgency is extreme and the stakes are financial, so ₹299 to avoid another six months of rejection is an easy yes. The outcome is visually provable (before/after resume, ATS screen) without touching a restricted category.",
 india_twist="India's job market is the perfect storm: huge fresher volume, ATS-driven screening, and job content that already performs massively on Indian Instagram. The differentiator is role-specificity ('resume for QA freshers', 'resume for BPO team lead') plus Naukri/LinkedIn specifics that US templates ignore. Watch the Meta Employment Special Ad Category and keep creative product-led.",
 proof_global="Star sellers in the resume category report 4,000–5,000+ purchases; templates sell at $8–$20 (bundles $15–$30) with ATS-friendly and easy-to-edit named as the top conversion factors; shops running 20–30 listings report $3,000–$6,000/month.",
 proof_india="Strong. Resume and LinkedIn content is one of the highest-engagement career themes on Indian Instagram; Indian digital-product guides list resume kits at ₹199–₹999; and the ₹2,000–₹7,000/month service upsell (resume rewriting for clients) is well documented in India.",
 comp_global="High but segmented by role and industry.",
 comp_india="High on generic 'ATS resume' packs, low on role-specific kits (data analyst fresher, testing, BPO, healthcare, teaching).",
 verify=[
  "Instagram India: search 'ATS resume', 'resume review' → count sellers, note prices and engagement on their reels",
  "Meta Ad Library (India): search 'resume template' → check for long-running ads and whether they're flagged as Employment category",
  "LinkedIn: look at how many 'resume services' run ads to Indian audiences (they're everywhere — that's proof of willingness to pay)",
 ],
 score_notes="India 8.36 (rank 5). Demand 9.5 and payment fit 10 (people pay instantly when a job is on the line), proof 8, ladder 8. Policy is 8 rather than 10 because of the Employment Special Ad Category, and competition 6 because everyone sells a resume template.",
 ladder_india="₹299 base kit → ₹499 bump: + cover letters + LinkedIn scripts → ₹999 upsell: interview bank + negotiation script → ₹1,499–₹4,999 1:1 review or 'job-search sprint'",
 ladder_global="$12 ATS resume template → $9 cover-letter/LinkedIn bump → $29 interview + LinkedIn kit → $97 job-search sprint course",
 hooks_india=["'Naukri pe 100 applications, reply nahi? Resume ATS mein atak raha hai.'",
               "'Fresher resume ki wo galti jo 90% karte hain.'",
               "'LinkedIn headline jo recruiter ko rok deta hai.'"],
 hooks_global=["'Your CV isn't bad. The robot can't read it.'",
               "'I sent 40 applications and got nothing. Here's what changed.'",
               "'Rewrite your resume in 20 minutes.'"],
 watch_india="Keep creative product-focused and avoid anything that looks like a job listing or 'we are hiring' — that pushes you into Meta's Employment Special Ad Category in India too, which shrinks targeting and can throttle delivery. Also: never promise a job or a salary figure.",
 watch_global="US advertisers: employment-adjacent creative can be pulled into the Employment Special Ad Category. Check current policy before spending.",
),
}
