# -*- coding: utf-8 -*-
"""Deep-dive content for ideas 11-20 (global order)."""

CONTENT_2 = {

"Faith-based devotionals, prayer journals & scripture study guides": dict(
 price_global="$7–$15 single · $19–$39 series",
 price_india="₹149–₹499 (reframed: festival & devotional printables)",
 aov_india="₹399–₹999",
 aov_global="AOV $20–$40 + annual series",
 contents=[
  "Global version: 30-day devotionals (day-numbered), prayer journals, scripture study workbooks, small-group discussion guides",
  "India version: festival puja vidhi cards, aarti/chant audio, 30-day gratitude journals, printable rangoli and mandala colouring, kids' festival activity books",
  "Diwali / Navratri / Ganesh Chaturthi decor printables: torans, rangoli stencils, gift tags, shubh-labh signs, greeting cards",
  "Corporate-gifting printables: Diwali greeting sets, sweet-box tags, branded festive cards (a real B2B add-on in India)",
  "A 'festival planner' — dates, shopping list, menu, decoration plan, guests",
 ],
 buyers_india="Families preparing for festivals, mothers organising puja and decor, kids' activity buyers, and small businesses needing Diwali greeting/gifting collateral.",
 buyers_global="Practising Christians broadly, plus under-served segments — Catholic/liturgical readers, women's ministry groups, small-group leaders, mums of young kids.",
 why_meta="Devotionals are bought in series and repeated annually, the audience is enormous and engaged, and it's one of the least-advertised big categories — so CPMs stay friendlier than business/finance.",
 india_twist="In India, the Western 'devotional journal' doesn't translate directly; festival and ritual printables do — and they're seasonal with brutal, predictable spikes (Diwali, Navratri, Raksha Bandhan, Ganesh Chaturthi, Holi). The B2B angle (Diwali corporate gifting kits sold to small businesses) is genuinely under-served and pays more per order.",
 proof_global="Devotionals 'sell in series; day-numbered formats do best' with very high repeat-buy ratings; Catholic/liturgical devotionals are called out as low-competition at $9–$15; 30-day Christian devotionals sit at $7–$14 with 'very high' repeat purchase.",
 proof_india="Medium. Indian festival printables and kids' activity packs sell seasonally at ₹99–₹499, and Diwali corporate gifting is a large, proven spend — but the digital version of this is early, so the evidence is market logic plus festival-season demand rather than documented bestsellers.",
 comp_global="Medium-low — genuinely under-advertised relative to audience size.",
 comp_india="Low-to-medium for festival printables; very low for good corporate-gifting kits in Hindi/regional languages.",
 verify=[
  "Instagram India: search 'Diwali printable', 'rangoli stencil', 'festival activity pack' → see who sells and at what price",
  "Meta Ad Library (India): run the same searches and look for seasonal ads that repeat every year (repeat = profitable)",
  "Ask 5 small businesses who they use for Diwali greeting cards — the answer is usually 'nobody' or 'a local printer'",
  "Etsy (global): 'devotional journal', 'prayer journal' → global evidence for the journal format",
 ],
 score_notes="India 6.50 (rank 16). Demand 6 and proof 4 for the journal format; policy 8; evergreen only 8 because Indian festival demand is spiky by definition. The corporate-gifting angle is the reason it stays on the list — a ₹999 B2B order beats ten ₹99 consumer orders.",
 ladder_india="₹199 festival printable kit → ₹499 bump: + kids' activity pack + decor → ₹999 upsell: complete festival bundle (DIY) → ₹499–₹4,999 corporate gifting licence (per business)",
 ladder_global="$9 30-day devotional → $19 companion journal bump → $29 full series → $49/yr devotional + planner subscription",
 hooks_india=["'Diwali ke liye decor print karo — ₹199 mein poora ghar.'",
              "'Bacchon ko festival ka matlab samjhao, screen ke bina.'",
              "'Rangoli stencils jo actually ban jaate hain.'"],
 hooks_global=["'Day 1 of 30: read this before your phone.'",
               "'A Lent devotional you can actually finish.'",
               "'The only journal my small group finished.'"],
 watch_india="Festival demand is 3–4 weeks long; if you miss the window, inventory of attention is zero. Also avoid using copyrighted images of deities from stock sites and avoid any prosperity/superstition guarantees in ad copy. Build the corporate-gifting B2B offer in September for a Diwali sell.",
 watch_global="Meta removed detailed religious-interest targeting years ago — creative must carry the targeting signal. Never imply the viewer's faith state.",
),

"GLP-1 companion guides & high-protein meal plans": dict(
 price_global="$9–$27",
 price_india="₹199–₹699 (reframed: Indian high-protein, PCOS/thyroid, diabetic-friendly diets)",
 aov_india="₹499–₹999",
 aov_global="AOV $27–$55",
 contents=[
  "India version: 60 Indian high-protein recipes with macros (paneer, dal, soya, curd, eggs, chicken) — made for Indian kitchens, not avocado toast",
  "Weekly meal plans with ₹ grocery lists for a family of 4 and a bachelor version",
  "PCOS / PCOD-friendly plan, thyroid-friendly plan, and a diabetic-friendly plan (with a clear 'not medical advice' disclaimer)",
  "Portion guide for the Indian thali (roti/rice/dal/sabzi ratios) and a 'protein per ₹100' comparison sheet",
  "Sugar-free dessert and snack swaps, festival-eating survival sheet (Diwali/Navratri/Eid)",
  "Global version: GLP-1 companion guide (what to eat on a smaller appetite, protein targets, grocery calculator)",
 ],
 buyers_india="Adults 28–45 managing PCOS/thyroid/pre-diabetes or trying to lose weight through diet, gym-goers chasing protein, and family cooks who plan the week's meals.",
 buyers_global="The millions on or coming off GLP-1 medication, plus the wider high-protein / '100g a day' crowd.",
 why_meta="One of the fastest-growing consumer behaviour shifts of the decade with an immediate, specific problem. Recipe content is the single most watchable ad format there is — food Reels get cheap reach.",
 india_twist="India is a *better* fit than the West for the diet angle and a worse fit for the GLP-1 angle (low GLP-1 penetration, high cost). The Indian mass market need is different: PCOS/PCOD, thyroid, pre-diabetes, sugar-free and 'protein kaise badhaye' — all enormous, all recurring. Keep the product food-first and never make reversal/cure claims.",
 proof_global="Diet-specific cookbooks and hormone/gut-health recipe products are named among the strongest-performing ebook categories ($4.99–$14.99); gut health + sleep optimisation is tracked at ~+74% YoY; niche cookbooks and diet plans are explicitly flagged as performing extremely well. Generic weight-loss titles are the most crowded shelf in the market.",
 proof_india="Medium-strong. Indian diet/recipe ebooks and 'diet plan' PDFs sell at ₹199–₹699 from Instagram sellers; PCOS and thyroid content is one of the highest-engagement health niches in India. Documented individual earnings aren't public, and refund risk is higher than other categories because results are emotional.",
 comp_global="High in the generic weight-loss lane, medium in the specific-diet lane.",
 comp_india="Medium — many dietitians sell plans; few sell a *printable systematic* product with grocery lists and swaps at an impulse price.",
 verify=[
  "Instagram India: search 'PCOS diet plan', 'protein recipes India' → see how many sell PDFs, at what price, and whether they're dietitians",
  "Meta Ad Library (India): search 'diet plan', 'meal plan' → check for long-running health ads (and note how careful the copy is)",
  "Check the compliance risk: read Meta's health & wellness policy page before you write creative",
 ],
 score_notes="India 7.25 (rank 12). Demand 7 and price fit 8 are strong, but policy safety 5 is the single biggest score-killer on the whole list — health claims get ads rejected and, in India, can attract regulator attention. It's ranked below its demand because it is hard to advertise, not hard to sell.",
 ladder_india="₹299 recipe pack → ₹599 bump: + weekly meal plans + grocery lists → ₹999 upsell: 8-week diet system (PCOS/thyroid/fat-loss variants) → ₹2,999 group challenge or 1:1 diet consult (with a qualified partner)",
 ladder_global="$14 50 high-protein meals → $9 grocery calculator bump → $37 8-week meal system → $19/mo weekly plan",
 hooks_india=["'Protein kaise badhaye — bina chicken ke bhi.'",
              "'PCOS hai? Ye 30 recipes try karo.'",
              "'Thali ka hisaab: roti, rice, dal — kitna kya?'"],
 hooks_global=["'On a GLP-1 and can't finish a plate? Eat this instead.'",
               "'100g of protein without a shake.'",
               "'What I meal-prep in 45 minutes for the week.'"],
 watch_india="Highest-risk idea on this list for India. Rules: no cure/reversal claims (no 'PCOS khatam'), no before/after body imagery, no specific weight-loss timelines, 18+ targeting, and a visible 'not medical advice' disclaimer. Never use 'aapko' + a health condition in the same line — that trips Meta's personal-attributes rule. If you partner with a dietitian for credibility, say so, and get their registration details right.",
 watch_global="Meta's health & wellness rules restrict weight-management creative, require 18+ targeting, and reject outcome/timeframe claims. Keep it food-first, never results-first.",
),

"Printable wall art, gallery-wall bundles & poster sets": dict(
 price_global="$3–$15 single · $19–$49 bundles",
 price_india="₹99–₹399 (low ticket, decoration & gifting)",
 aov_india="₹299–₹699",
 aov_global="AOV $18–$35",
 contents=[
  "Theme bundles: nursery/kids, minimal line art, shloka & Sanskrit quotes, motivational Hinglish, boho/floral, spiritual (mantra, mandala), festive decor",
  "Gallery-wall sets (6–9 coordinated prints) with layout guides",
  "Multiple aspect ratios (A4/A3, 4:5, 2:3) so buyers can print locally without resizing",
  "Frame/layout mockups so the buyer can visualise it on their wall",
  "A 'print at your local shop' instruction sheet (₹ cost guide) — hugely appreciated in India",
 ],
 buyers_india="New-home decorators in metros, nursery decoration for new parents, hostel/PG students, gifting buyers, and small cafes/offices decorating on a budget.",
 buyers_global="Renters and first-home decorators on a budget, nursery/new-parent buyers, gift buyers, small businesses decorating a space.",
 why_meta="Highest raw volume of any digital category and the easiest price-anchor ad in existence ('print it for ₹99 vs buy it for ₹2,000'). Cheap to make, instantly delivered, and re-buys on the seasonal decor cycle.",
 india_twist="India works, but the ceiling is lower: ₹99–₹299 per set, and the winner is spiritual/festive/nursery/traditional art rather than Western minimalism. The customer also needs local-print instructions or they'll complain. This is a volume, catalogue and seasonal-drop business, not a one-product business.",
 proof_global="Printables/wall art is consistently the #1 digital-download category by volume on Etsy — digital downloads estimated at $1.2B+/yr with 80–95% margins and $3–$15 typical prices — with gallery-wall sets and bundles outperforming single pieces. 2026 style shift: maximalist botanical and dark moody abstract replacing minimalism.",
 proof_india="Medium. Indian sellers do sell printable decor and nursery art at ₹99–₹399, mostly from Instagram and Etsy; demand rises sharply around Diwali/house-warming/new-year. Documented Indian seller earnings are usually in the ₹10k–₹40k/month band, not headline numbers.",
 comp_global="The most saturated category on this list and the easiest to have stolen.",
 comp_india="High for generic quotes, low for genuinely Indian styles (shloka art, madhubani-inspired, festival decor, Indian nursery art).",
 verify=[
  "Etsy: 'printable wall art' → note how many listings have 5,000+ sales (proves volume) and how low prices are (proves the ceiling)",
  "Instagram India: search 'printable wall art India', 'nursery prints' → see price points and style gaps",
  "Meta Ad Library (India): search 'wall art printable' → check whether anyone runs this continuously",
 ],
 score_notes="India 6.46 (rank 17). Demand 6, price 6, competition 4 — in India this is a low-price, high-volume, highly-copied business with no upsell path. It earns its place as a *catalogue filler* and a fast first product, not as a business.",
 ladder_india="₹99 single set → ₹299 bump: gallery-wall bundle (6 prints) → ₹599 seasonal pack → ₹999/yr print club (4 seasonal drops)",
 ladder_global="$7 print set → $15 gallery-wall bump → $29 seasonal bundle → $39/yr print club",
 hooks_india=["'₹100 mein ghar ka look badal do — bas print karo.'",
              "'Nursery decor, ready to print.'",
              "'Diwali ke liye 10 prints, ₹199.'"],
 hooks_global=["'£3 versus £80 for the same wall.'",
               "'Gallery wall in 10 minutes — all 6 prints below.'",
               "'December is coming. Print this set now.'"],
 watch_india="Never enter with generic minimal quote prints — that market is dead on price. Win with Indian-specific art, festive drops and bundles, and always include print instructions (Indian buyers print at local shops, not at home, so sizing must be simple).",
 watch_global="Saturated and easy to steal. Win with a distinctive style, a following, or a seasonal drop calendar.",
),

"Personalised kids' storybooks & AI-made personalised gifts": dict(
 price_global="$15–$39",
 price_india="₹299–₹1,499 (gifting & birthday market)",
 aov_india="₹599–₹1,999",
 aov_global="AOV $30–$70",
 contents=[
  "Personalised story PDF: child's name, photo and a chosen theme (birthday, first day of school, festival, new sibling, bravery)",
  "5–10 story variants so buyers can order repeatedly for siblings, cousins and friends",
  "Hindi + English versions (a genuine differentiator in India)",
  "Audio narration option (parent's voice or AI) — the feature that makes it feel magical",
  "Printable + iPad-ready format, with a gift-wrap card and a 'read together' activity page",
  "Optional printed-and-delivered version via a local print partner (higher ticket)",
 ],
 buyers_india="Parents buying for their own child's birthday, relatives and friends buying birthday gifts, grandparents, and school/creche gifting (bulk orders).",
 buyers_global="Parents, grandparents, godparents, aunts/uncles shopping for a birthday.",
 why_meta="Emotional, gifting-driven, high perceived value and impossible to comparison-shop — 'your child is the hero of this book' converts on sight, and personalisation justifies 2–3× the price of an equivalent generic product.",
 india_twist="India is a strong fit because the gifting culture is intense and a ₹499 personalised gift beats yet another toy. The winning hooks are festivals and birthdays, and Hindi/bilingual versions are almost unserved. The constraint is fulfilment: you must automate name/photo insertion before you advertise, or the business breaks at 20 orders a day.",
 proof_global="Personalised kids' storybooks are documented at 50,000+ sales in creator reports — described as an emotional purchase with high perceived value that scales with automation; AI-assisted personalisation is called out as the fastest-growing Etsy wave (+240% YoY for AI-assisted digital products).",
 proof_india="Medium-strong. Personalised gifting is a large, proven Indian spend (photo books, mugs, frames), and digital-first personalised story PDFs are early but growing; birthday-party and festival gifting demand is not in question. Documented Indian digital storybook sellers exist but are small.",
 comp_global="Medium — the operational barrier keeps lazy sellers out.",
 comp_india="Low-to-medium, and very low for Hindi/regional-language personalised books.",
 verify=[
  "Instagram India: search 'personalised story book', 'birthday gift personalised' → note prices (₹399–₹1,499) and how sellers take orders (DM/Google Form)",
  "Meta Ad Library: search 'personalised book' → check which countries advertisers run this in and how long they've been running",
  "Test the operation yourself: can you produce one book in under 10 minutes? If not, fix that before spending on ads",
 ],
 score_notes="India 7.44 (rank 10). Demand 7 (gifting is huge, but the occasion is occasional), proof 5 (few documented Indian sellers), ladder 7, policy 8. It ranks mid-table mainly because each sale needs a personalised step — profitable per order, harder to scale than a PDF.",
 ladder_india="₹499 single personalised story → ₹899 bump: + audio narration + activity pages → ₹1,499 sibling/family bundle → ₹2,499 printed + digital gift set (local print partner)",
 ladder_global="$19 single book → $29 sibling version bump → $49 printed + digital bundle → $15 seasonal edition",
 hooks_india=["'Beti ka naam hero ban gaya — 5 minute mein.'",
              "'Birthday gift jo bachcha bhool nahi payega.'",
              "'Hindi mein personalised storybook.'"],
 hooks_global=["'I made my daughter the main character of her bedtime story.'",
               "'The birthday gift that made a 6-year-old cry.'",
               "'Type a name, get a book in 60 seconds.'"],
 watch_india="Build the automation first: a form → templated page generation → PDF delivery flow. If you do it manually, a viral reel destroys you. Also avoid any celebrity/cartoon likeness (a big temptation in India) and any AI illustration of a real child's photo that looks creepy rather than charming — test with 10 parents before scaling.",
 watch_global="AI illustration style must stay consistent and you must hold commercial rights. No franchise likeness.",
),

"Certification & exam-prep cheat sheets (licence, board, bootcamp)": dict(
 price_global="$9–$24",
 price_india="₹99–₹999 (sweet spot ₹199–₹499) — the biggest India opportunity",
 aov_india="₹499–₹1,999 (test series and yearly packs)",
 aov_global="AOV $25–$60",
 contents=[
  "Exam-wise high-yield notes: state PSC (RPSC/MPSC/UPPSC), SSC, banking, railways, police, REET/CTET, Patwar, teaching, defence",
  "Previous-year question analysis — which topics actually repeat, with frequency tables",
  "One-liner revision PDFs (500–1,000 facts) and Hindi + English versions of every sheet",
  "Monthly current-affairs compilation with a quiz, updated every month (this is your recurring revenue)",
  "Mock tests / practice sets with solutions and a score tracker",
  "A 'last 30 days' study plan and a syllabus map so the buyer knows exactly what to skip",
 ],
 buyers_india="Aspirants preparing for state and central government exams — especially in Rajasthan, UP, MP, Bihar (huge volume, low price tolerance, high urgency), plus their parents who pay.",
 buyers_global="Real-estate licence candidates, PMP/IT cert candidates, nursing & teaching boards, coding-interview preppers, apprenticeship exams.",
 why_meta="The most economically rational purchase on this list: the buyer is already spending heavily on their attempt, so ₹199 for high-yield notes is noise in their budget. The audience refreshes every exam cycle, forever.",
 india_twist="India is by far the strongest market for this idea — India *is* the exam-prep market. The competition is also the most brutal (Telegram is full of free PDFs, and coaching giants dominate), so you cannot win by selling information. You win with: exam specificity (REET Level-2 SST, RPSC AEN, Patwar), language (Hindi/regional), recency (updated current affairs), and format (one-liners, mock tests, a 40-day plan). Sell subscriptions and updates, not static files.",
 proof_global="'Certification exam cheat sheets' is named among emerging micro-niches with almost no competition in 2026 niche analysis; exam-prep/study guides hold $9.99–$24.99; the related role-specific automation niche is tracked at ~+210% YoY.",
 proof_india="Strong on market size, medium on individual benchmarks: paid test-series and notes subscriptions (Testbook, Adda247, Unacademy and hundreds of smaller players) prove mass willingness to pay; free Telegram PDF culture proves the format is consumed; and Indian guides list study-note PDFs at ₹149–₹399 as a top-selling digital product type. Note the same guides also show how crowded it is.",
 comp_global="Medium — the niche is specific enough to avoid Etsy saturation.",
 comp_india="The most competitive idea in this document for India: one directory lists 765+ UPSC Telegram channels alone, with individual channels at 90k–600k subscribers giving away free material. You must pick a *sub-niche* (one exam, one state, one language) or you'll be invisible.",
 verify=[
  "Telegram: search your exam name → count channels, subscribers, and whether any sell paid access (that's your model proof)",
  "YouTube: search '[exam] strategy' → see view counts; the audience size is right there",
  "Instagram India: search 'REET notes', 'Patwar notes' → check prices in bios (₹99–₹499 is typical)",
  "Check Testbook/Adda247 pricing for the same exam → your ceiling and your credibility benchmark",
  "Download 3 free PDFs from Telegram → if they're bad, that's your opening; if they're good, pick a narrower exam",
 ],
 score_notes="India 8.67 — fourth overall, and the single biggest *market-size* play in this document. Demand 10, proof 9, price fit 9, payment 10. Competition 4 and IG fit 8 (exam content is easy to make, hard to make exciting) are the drags. It ranks below weddings and Canva because ad costs in education run higher (India EdTech CPM ₹160–₹340 with parent-targeting even hotter).",
 ladder_india="₹99 one-liner pack (single subject) → ₹299 bump: PYQ analysis + mock set → ₹999 upsell: full-subject bundle → ₹1,499–₹1,999/yr membership (monthly current affairs + test series) → ₹4,999 crash-course cohort",
 ladder_global="$12 high-yield cheat sheet → $19 practice-question pack bump → $39 full prep bundle → $79 cohort/mock-exam subscription",
 hooks_india=["'REET/PATWAR ke liye 40-din ka plan — jo actually follow hota hai.'",
              "'Ye 100 one-liners har paper mein aate hain.'",
              "'Rajasthan GK — sirf yahi padho, baaki chhod do.'"],
 hooks_global=["'The 40 facts that show up in almost every [exam] sitting.'",
               "'I passed [exam] in 3 weeks while working full time.'",
               "'Which study resource would I buy again? Only this one.'"],
 watch_india="Three India-specific landmines: (1) copyright — never republish coaching-material PDFs, NCERT scans or paid test series; write original content; (2) accuracy — one wrong answer in a mock test triggers a review storm, so have a subject expert verify; (3) leakage — Telegram forwarders will pirate a static PDF within days, which is exactly why your product should be a *monthly-updated subscription + tests*, not a one-time file. Also avoid claiming 'guaranteed selection' or implying affiliation with any exam body.",
 watch_global="You must know the exam. Write original questions; some boards assert IP over formats.",
),

"Notion / business 'operating system' templates": dict(
 price_global="$15–$79",
 price_india="₹499–₹1,999 (freelancers & agencies)",
 aov_india="₹999–₹2,499",
 aov_global="AOV $40–$90",
 contents=[
  "Client CRM with pipeline stages, follow-up reminders and a lead-source tracker",
  "Invoice + payment tracker built with Indian reality in mind (GST column, UPI reference, part-payments, TDS note)",
  "Project board with scope-creep tracker and deliverables checklist",
  "Content calendar + idea vault for the creator/freelancer side of the business",
  "SOP library template and onboarding questionnaire for new clients",
  "Expense & profit tracker (₹), plus a 20-minute Hinglish setup video and a filled-in example workspace",
 ],
 buyers_india="Freelancers (designers, editors, developers, writers), small agencies, coaches and consultants, and creators who have outgrown notes and spreadsheets.",
 buyers_global="Freelancers, VAs, small agencies, coaches, realtors, content creators — people running a business from a laptop.",
 why_meta="The highest upsell ceiling on this list: the template is the entry drug to a ₹2,000 course, a ₹5,000/mo community or a ₹25,000 done-for-you setup. Buyers are buying time, so they tolerate higher prices.",
 india_twist="India's freelancer and small-agency population is exploding, and Indian-specific friction (GST invoices, UPI reconciliation, TDS, client payment delays) is completely un-addressed by Western templates. That's the moat. Distribution is harder than in the US — Indian freelancers don't browse Etsy for Notion systems, so you need Instagram/YouTube demos and a Hinglish tutorial.",
 proof_global="In a 200,000-product Gumroad analysis, productivity systems (Notion templates/dashboards) were among the most likely to earn — 46.3% make money, averaging ~$9,986 — with profession-specific client-management and agency OS templates outperforming generic dashboards; Notion templates consistently rank among the best-selling digital products across Gumroad and Etsy.",
 proof_india="Medium. Notion adoption in India is growing fast (especially in startups and among freelancers), Indian guides list Notion templates at ₹299–₹1,499, and 'Sell Notion templates India' content exists from Indian creator educators. No documented Indian bestseller, and most Indian freelancers still use Google Sheets — so pair the Notion version with a Sheets version.",
 comp_global="High — and Notion's own free template gallery caps the low end.",
 comp_india="Medium: very few India-specific (GST/UPI/Hindi) business OS templates exist.",
 verify=[
  "Gumroad Discover: search 'Notion' → note sales counters on top products",
  "Instagram India: search 'Notion template India', 'freelancer CRM' → see who sells and at what price",
  "Check the freelancer audience size: search LinkedIn/Instagram for 'freelancer India' community sizes",
 ],
 score_notes="India 6.84 (rank 15). Demand 6 (niche audience), proof 5, price fit 6 — Indian freelancers pay for tools but convert slowly on ₹999+ Notion systems, and Sheets is the default. Policy 9 and payment 10 keep it safe; it ranks where it does because the audience, not the product, is the constraint.",
 ladder_india="₹499 freelancer tracker → ₹999 bump: + client CRM + invoice/GST pack → ₹1,999 upsell: full agency OS + Hinglish setup video → ₹4,999/mo community or ₹25,000 done-for-you setup",
 ladder_global="$29 client-management template → $39 onboarding + SOP bump → $89 full agency OS → $199 course or $99/mo community",
 hooks_india=["'Client payment late? Ye tracker follow-up khud karwata hai.'",
              "'Freelancer ka poora business, ek dashboard mein.'",
              "'GST invoice + UPI tracking — Notion mein.'"],
 hooks_global=["'My whole agency runs on one page.'",
               "'If you're still tracking clients in your notes app, watch this.'",
               "'I've duplicated this 240 times. Here's what's inside.'"],
 watch_india="Indian buyers need setup help — include a Hinglish video or your refund rate will be high. Also offer the Sheets version; forcing Notion on a Sheets user loses the sale. Never claim GST-compliance certification for your template; add a CA-review note instead.",
 watch_global="Notion's free-template ecosystem and YouTube tutorials cap what you can charge for an obvious dashboard. Win with profession specificity and packaging.",
),

"Crochet / knitting patterns & SVG craft files": dict(
 price_global="$3–$12 patterns · $2–$8 SVG",
 price_india="₹99–₹499 (reframed: mehndi, aari, blouse patterns, tailoring, craft designs)",
 aov_india="₹299–₹999",
 aov_global="AOV $15–$30",
 contents=[
  "India version: 100+ mehndi design sheets (simple→bridal, festival + Arabic + Rajasthani), aari/embroidery design books, blouse and kurta cutting patterns in multiple sizes, tailoring measurement charts",
  "Global version: crochet/knitting patterns with step photos, and SVG/DXF cut files for Cricut/Silhouette",
  "Printable practice sheets (mehndi tracing sheets, embroidery stitch practice grids, rangoli design grids)",
  "Bundles by occasion: bridal season, festival (Karva Chauth, Teej, Diwali), kids' craft",
  "A short technique video (how to hold the cone, how to read the pattern) — the difference between a refund and a repeat customer",
 ],
 buyers_india="Women 18–45 who do or learn mehndi, tailoring students and home-tailors, aari/embroidery workers, small craft businesses, and boutique owners looking for designs.",
 buyers_global="Crocheters and knitters (a huge, very online, repeat-purchase hobby base), Cricut/Silhouette crafters, small craft sellers.",
 why_meta="Almost pure passive income: makers buy patterns repeatedly, month after month. The winning play isn't one bestseller — it's a large catalogue, which is exactly what the algorithm rewards.",
 india_twist="India's version of this category is craft *design* delivery, and it's genuinely under-served digitally: mehndi design books, blouse patterns and aari designs sell well to a Tier-2/3 female audience that pays via UPI and learns from Instagram/YouTube. Language (Hindi) and print-friendliness (A4, tracing-friendly) matter more than design sophistication. Prices are low but repeat purchases are high.",
 proof_global="Digital patterns (crochet/knitting/sewing) hold $3–$25 with low competition and medium repeat buying; SVG cut files show 200–800 sales/month at $2–$8 with very high repeat purchase; crochet and knitting patterns appear on Etsy bestseller lists year-round.",
 proof_india="Medium-strong. Mehndi design and tailoring-pattern PDFs are sold widely by Indian Instagram sellers and on marketplaces at ₹99–₹499, often in bundles; tailoring/design courses and pattern books are a proven Indian category offline, which supports the digital version.",
 comp_global="Medium-high on Etsy; the barrier is consistency and catalogue size, not competition per se.",
 comp_india="Low-to-medium — much lower competition than Canva or exam notes, and almost nobody serves it in Hindi with good print files.",
 verify=[
  "Instagram India: search 'mehndi design pdf', 'blouse pattern', 'aari work designs' → note prices and how sellers package/download",
  "Meta Ad Library (India): search 'mehndi design', 'blouse pattern' → check active advertisers and longevity",
  "YouTube: search 'mehndi design' → view counts prove the audience",
 ],
 score_notes="India 7.85 (rank 8) — the quiet over-performer. Demand 8, competition 6, policy safety 10 (no claims, no regulation), payment 10, evergreen 8. It loses points only on price fit (7) and ladder depth (7): ₹199 files need bundles and memberships to make real money.",
 ladder_india="₹149 single design pack → ₹399 bump: + 3 packs (bridal + festival + kids) → ₹799 upsell: full library + technique videos → ₹1,499/yr membership (monthly new design drop) or ₹2,999 course",
 ladder_global="$5 pattern → $15 five-pattern bundle bump → $29 seasonal pattern club → $8/mo membership",
 hooks_india=["'100 mehndi designs — print karo, practice karo.'",
              "'Blouse pattern jo har size mein fit ho.'",
              "'Aari work ke 50 designs, ek PDF mein.'"],
 hooks_global=["'One skein. One evening. This is the whole pattern.'",
               "'The mistake every beginner makes on row 3.'",
               "'Cricut users: 20 files you'll use all December.'"],
 watch_india="Price floor is low, so this only works as a bundle/catalogue/membership play — a ₹99 single pack can't carry ad spend. Also piracy: mehndi/pattern PDFs get forwarded heavily, so sell bundles, updated editions and video, and use re-issueable delivery links. Never copy designs from published books or other sellers' PDFs; that's the most common takedown in this category.",
 watch_global="A $3 pattern cannot carry cold Meta traffic alone. Enter as a bundle/membership play or organic-first.",
),

"Perimenopause / hormone-health trackers & doctor-visit kits": dict(
 price_global="$9–$25",
 price_india="₹199–₹599 (reframed: PCOS/thyroid/women's health trackers)",
 aov_india="₹499–₹1,499",
 aov_global="AOV $25–$60",
 contents=[
  "Symptom tracker (cycle, sleep, mood, energy, weight, hair/skin) with a 90-day view so patterns become visible",
  "Doctor-visit prep kit: a one-page summary the patient fills in and hands to the doctor, plus the questions to ask",
  "India version: PCOS/PCOD tracker, thyroid tracker (TSH/T3/T4 log with dates), and an Iron/vitamin-D + lab-report organiser",
  "Lifestyle sheets: sleep, stress, movement, and food-trigger logging (non-medical, non-prescriptive)",
  "A partner/family explainer page — 'how to support someone going through this'",
  "Printable + phone-friendly versions",
 ],
 buyers_india="Women 28–48 dealing with PCOS/PCOD, thyroid issues, hair loss, irregular cycles or fatigue; and family members trying to help.",
 buyers_global="Women 38–55 navigating symptoms with no clear medical pathway, plus partners/adult children buying for them.",
 why_meta="Textbook underserved demand: an enormous, affluent, ignored audience sitting between 'free app' and 'expensive clinic'. A structured tracker plus a doctor-visit prep sheet is a genuinely novel product, not another planner reskin.",
 india_twist="India's version is PCOS/PCOD and thyroid — enormous, chronically under-served, and highly engaged on Instagram. The product must be strictly *organisational* (tracking, preparing for appointments, organising lab reports), never diagnostic or prescriptive, because Indian health-ad enforcement and consumer-protection exposure are real.",
 proof_global="Analysts flag 'desperate' demand with nothing structured between free apps and expensive clinics, specifically naming perimenopause symptom trackers with doctor-visit prep; perimenopause is listed as an under-served ebook topic for women 38–50; women's health is repeatedly identified as a category gap.",
 proof_india="Medium. PCOS/thyroid content is one of the most engaged women's-health niches in India and dietitians/coaches sell plans at ₹500–₹5,000; a structured *tracker* (rather than advice) is early and mostly un-served digitally. Treat demand as high and competition as low, with policy as the constraint.",
 comp_global="Low — genuinely under-built relative to audience size.",
 comp_india="Low for trackers; medium for diet/lifestyle plans from qualified practitioners.",
 verify=[
  "Instagram India: search 'PCOS tracker', 'thyroid diet plan' → see what's sold, what's free, and who has authority",
  "Meta Ad Library (India): search 'PCOS' / 'thyroid' → note how few ads run and how carefully they're worded",
  "Read Meta's health policy page and the India advertising-claims guidance before writing anything",
 ],
 score_notes="India 6.05 (rank 20) — bottom of the list, and the reason is policy, not demand. Policy safety 5, proof 4, demand 5 (the buying identity is smaller in India than the suffering population, and free gyaan is everywhere). It stays on the list as a high-upside, low-competition play for someone with clinical credibility.",
 ladder_india="₹299 PCOS/thyroid tracker → ₹599 bump: + doctor-visit prep kit + lab organiser → ₹1,499 upsell: 90-day lifestyle system (non-medical) → ₹4,999 group programme with a qualified dietitian partner",
 ladder_global="$14 symptom tracker + doctor prep → $19 'what to ask your GP' bump → $39 8-week protocol bundle → $19/mo community",
 hooks_india=["'Doctor ke paas jaane se pehle ye page bharo.'",
              "'3 mahine ka pattern — ek tracker mein.'",
              "'Reports, symptoms, dates — sab ek jagah.'"],
 hooks_global=["'Go to your appointment with this, not a vague description.'",
               "'I tracked this for 90 days. The pattern was obvious.'",
               "'The 12 questions that got me taken seriously.'"],
 watch_india="Never claim to diagnose, treat, cure or 'balance hormones'. No before/after, no 'aapko ye problem hai' personal-attribute framing, 18+ targeting only. Get a qualified gynaecologist or dietitian to review the content and credit them — in India that credibility is also your best differentiator, and it protects you if a buyer complains.",
 watch_global="Health rules apply: 18+ targeting, no symptom or cure claims, no second-person health framing. Sell organisation, not treatment.",
),

"Faceless-instagram / theme-page growth guides + MRR-PLR resell packs": dict(
 price_global="$7–$41",
 price_india="₹199–₹1,999 (huge demand, huge trust problem)",
 aov_india="₹499–₹2,999",
 aov_global="AOV $30–$90",
 contents=[
  "Niche selection framework with India-specific niches (finance, motivation, devotional, meme, AI tools, education)",
  "30-day content plan with 100 hook templates and a Canva/CapCut production workflow",
  "Instagram growth playbook: profile setup, reel formats, hashtags vs SEO, comment-to-DM automation (ManyChat), posting rhythm",
  "Monetisation module: product creation, ₹ pricing, UPI checkout setup, WhatsApp funnel, affiliate income",
  "MRR/PLR bundle version: rebrandable templates and ebooks with a clear licence sheet explaining exactly what the buyer may resell",
  "A 60-minute walkthrough video and a private doubt-clearing group (the real retention driver)",
 ],
 buyers_india="18–30 year olds wanting a side income without showing their face — students, small-town youth, homemakers, and job-holders wanting a second stream.",
 buyers_global="People who want a side income and don't want to show their face — a group already being advertised to on Instagram.",
 why_meta="This is the category that most aggressively advertises on Meta, which is both why it works and why to be careful. The buyer is the same person the ad targets, the price is tiny, and the pitch is trivially testable.",
 india_twist="India is this category's biggest market and its most damaged one. Demand is enormous and the content is proven, but the niche is thick with unrealistic income promises, rebranded junk MRR files and refund demands — and Meta's income-claim enforcement is tightening. The only durable version in India is skill-first: teach a real workflow (content, hook, monetisation), show your own account's numbers honestly, and deliver a community so the buyer actually executes.",
 proof_global="Faceless marketing guides with MRR/PLR rights sell at $4–$41 across Etsy and independent stores using exactly the 'buy it, learn it, rebrand it, resell it for 100% profit' positioning; guides and planners with resale rights are listed among Etsy's top-selling digital products in 2026. Caveat: side-hustle/online-income reader trust is explicitly flagged as low, and the niche shows cooling momentum (0.73).",
 proof_india="Strong demand evidence, weak trust evidence. Indian digital-product and 'faceless page' creators sell courses at ₹499–₹4,999 and guides at ₹199–₹999 heavily on Instagram, and India has one of the largest creator-economy growth rates in the world (25–30% annually). But documented refund/chargeback complaints and the cooling global momentum of the 'make money online' niche mean this needs a genuine product to survive.",
 comp_global="Extremely high — the most advertised and most cloned category here.",
 comp_india="Extremely high on generic 'make money' courses; medium for genuinely skill-first, niche-specific guides with real proof.",
 verify=[
  "Meta Ad Library (India): search 'digital product course', 'faceless page' → count active advertisers (dozens) and scrutinise their claims",
  "Instagram India: search 'faceless page India', 'digital product seller India' → note price points and how many sellers have large followings but no proof",
  "Look for the refund trail: search reviews/Reddit for the specific seller names you find",
 ],
 score_notes="India 7.92 (rank 7) — high on raw opportunity. Demand 9, IG fit 10 (it's literally an Instagram-native product), price fit 8. But policy 5, competition 3 and proof 8-against-low-trust make it the most dangerous idea in the top 10. Ranking it 7th reflects demand, not comfort.",
 ladder_india="₹199 starter ebook → ₹499 bump: + template pack + 30-day plan → ₹1,999 upsell: full course + private group → ₹4,999+ done-with-you or monthly membership",
 ladder_global="$7 ebook → $17 resell-rights bump → $37 bundle → $97/mo mentorship",
 hooks_india=["'Bina face dikhaye page chala kar paise — sach kya hai?'",
              "'1,000 followers se pehle ye 3 cheezein set karo.'",
              "'Content ka hook bigda hai, niche nahi.'"],
 hooks_global=["'I built this page without ever showing my face.'",
               "'You can resell this as your own — here's how it works.'",
               "'3 reasons your theme page isn't converting (it's not the niche).'"],
 watch_india="The highest-risk idea in this document for India. No income guarantees ('₹1 lakh/month' will get rejected and may invite consumer complaints), no fake income screenshots, and if you sell resale rights, state exactly what the licence permits — selling rights you don't own is a legal problem, not just a policy one. The honest framing ('this is a skills course; results depend on your work') protects both your ads and your reputation.",
 watch_global="Income-claim ads get rejected, MRR products are often rebranded copies with no IP, and refund rates run high. Sell a real skill with real proof.",
),

"Manifestation, shadow-work & spiritual journals": dict(
 price_global="$7–$18",
 price_india="₹149–₹499 (reframed: gratitude, LOA, astrology & vastu printables)",
 aov_india="₹399–₹999",
 aov_global="AOV $18–$35",
 contents=[
  "India version: 21/30-day gratitude & manifestation journals, affirmation card decks (Hindi + English), sankalp/goal-setting pages, moon-cycle ritual tracker",
  "Astrology & numerology printables: panchang-friendly planner pages, birth-chart workbook (blank), vastu room-checklist, rudraksha/ mantra journal",
  "Global version: shadow-work prompts, inner-child journaling, guided self-reflection workbooks",
  "Printable affirmation cards, wall posters and phone wallpapers as a bundle add-on",
  "A 'how to actually use this' page, because blank journals get abandoned and unnamed refunds follow",
 ],
 buyers_india="Women 18–40 in metros and Tier-2 cities into gratitude, manifestation, law-of-attraction, astrology and vastu content; plus gifting buyers around birthdays and New Year.",
 buyers_global="Women 18–40 into manifestation, journaling, 'soft life' and aesthetic spirituality, plus gift buyers.",
 why_meta="Aesthetic, emotional, identity-driven, near-zero production cost, and one of the highest repeat-purchase rates in the journal category. Creative is cheap: pages, sunlight, a pen — and in India, festival/astro styling performs even better.",
 india_twist="India has a unique advantage: astrology, vastu, numerology and mantra culture are mainstream, not fringe — so the addressable audience is much bigger than the Western 'manifestation' niche. But saturation of free affirmation content is extreme, price ceilings are low (₹149–₹299), and drift into superstition claims creates policy and credibility risk. Sell aesthetics, ritual and structure; avoid promising outcomes.",
 proof_global="Manifestation & shadow-work journals are rated 'very high' repeat buying on Etsy at $7–$12; guided journals are named among the strongest Etsy journal niches; mental-health-adjacent journaling workbooks ($9–$24) are flagged as one of the fastest-growing niches of the last 18 months.",
 proof_india="Medium. Gratitude journals and affirmation decks sell in India both digitally (₹149–₹499) and physically, and astro/vastu content has massive engagement; but there are no documented Indian digital bestsellers at scale, and most of the money in this space goes to astrologers selling consultations rather than journals.",
 comp_global="Severe — the most-cloned aesthetic niche on Etsy.",
 comp_india="High on affirmations, low on well-designed astro/vastu printables in Hindi.",
 verify=[
  "Instagram India: search 'gratitude journal pdf', 'affirmation cards', 'vastu checklist' → prices and repetition tell you the saturation level",
  "Etsy: 'manifestation journal', 'shadow work journal' → global sales evidence",
  "Meta Ad Library (India): search 'affirmation cards' / 'gratitude journal' → check longevity of ads",
 ],
 score_notes="India 6.89 (rank 14). Demand 7 and IG fit 8 are decent, price fit 7, but competition 5, proof 5 and policy 6 (astrology/superstition claims and health-adjacent mood claims are the risk) hold it down. A solid catalogue/add-on product, not a lead product.",
 ladder_india="₹199 gratitude journal → ₹399 bump: + affirmation cards + wallpapers → ₹699 upsell: 'ritual kit' (journal + astro planner + vastu checklist) → ₹999/yr revised edition or workshop",
 ladder_global="$9 journal → $15 prompt cards/sticker bump → $29 complete ritual kit → $49/yr revised edition",
 hooks_india=["'21 din ki gratitude journal — sach mein farak padta hai.'",
              "'Affirmation cards jo actually use hote hain.'",
              "'Ghar ka vastu checklist — print karke laga do.'"],
 hooks_global=["'Day 1 of 21. Write this before you check your phone.'",
               "'Shadow work prompts that aren't cringe.'",
               "'The journal I've refilled 4 times.'"],
 watch_india="Never promise outcomes (money, marriage, health) — that's both a Meta policy risk and, in India, a consumer-complaint risk. Don't imply the viewer's psychological or spiritual state ('aap stuck ho?'), keep astrology content framed as cultural/reflective rather than predictive, and avoid copying copyrighted temple/deity art.",
 watch_global="Severe saturation plus Meta's personal-attributes rule. Sell the ritual, not the reader's wounds.",
),
}
