#!/usr/bin/env python3
"""GLOBAL SCORE DATA (pure module, no side effects).
Holds the 20 ideas, their global 1-10 scores and the global weighting.
The India scores live in build.py; the descriptive content lives in content_1.py / content_2.py.
Run build.py to regenerate all outputs.

Scoring model (0-10 per factor, weighted):
  demand        20%  how many buyers exist with an active, felt problem / desire
  meta_fit      18%  how well it advertises on Instagram/Facebook cold traffic (hook, demo, impulse)
  money_proof   15%  documented evidence real sellers are getting paid (sales counts, revenue reports)
  upsell_ladder 12%  can you stack AOV (order bump -> upsell -> subscription/community)
  margin_ease   10%  delivery simplicity, support load, gross margin
  speed_to_launch 8% how fast a sellable v1 ships
  policy_safety  7%  Meta ad-policy risk (health/finance/income claims)
  low_competition 6% inverse of saturation
  evergreen      4%  year-round vs seasonal demand
"""


FACTORS = [
    ("demand", 0.20, "Demand"),
    ("meta_fit", 0.18, "Meta-ad fit"),
    ("money_proof", 0.15, "Money proof"),
    ("upsell_ladder", 0.12, "Upsell ladder"),
    ("margin_ease", 0.10, "Margin & ease"),
    ("speed_to_launch", 0.08, "Speed to launch"),
    ("policy_safety", 0.07, "Policy safety"),
    ("low_competition", 0.06, "Low competition"),
    ("evergreen", 0.04, "Evergreen"),
]

# id, name, category, price, aov, scores, buyers, why, evidence, funnel, hooks, watch
P = [
 dict(
  name="Budget systems, cash-stuffing kits & debt-payoff spreadsheets",
  category="Money & personal finance",
  price="$7–$29 digital · $19–$49 binder bundles",
  aov="AOV $19–$35 with bump + upsell",
  scores=dict(demand=10, meta_fit=9, money_proof=10, margin_ease=9, upsell_ladder=9, speed_to_launch=10, policy_safety=8, low_competition=5, evergreen=9),
  buyers="Women 22–45 on a tight paycheck, cash-stuffing / sinking-fund TikTok+Reels viewers, debt-payoff community, couples merging finances",
  why="Payday anxiety is universal, the aesthetic is built for Reels (pastel binders, envelope stuffing, cash counting), and the buyer is impulsive at $9–$17. It is the single best-documented low-ticket digital category on Meta.",
  evidence="Pretty Arrow (Emily McDermott): 30,000+ shop sales, first spreadsheet hit $5K/month in 3 months and $15K/month in 6 months — she names Facebook ads as a traffic channel. Etsy 'Excel budget templates' top-100 listings average ~3.0M monthly views at ~$5.36. Cash-stuffing / sinking-funds trend covered by mainstream finance media through 2026 as a still-growing social trend.",
  funnel="$9 'paycheck plan' printable -> $19 cash-stuffing binder bundle bump -> $37 'debt payoff vault' (spreadsheets + video) -> $9/mo printable club",
  hooks=["'Your paycheck disappears in 3 days. Here's the $9 system that fixed it.'",
         "'Cash stuffing won't work with these 4 envelopes — swap them.' (demo)",
         "'Before payday I do these 5 things. Printable in bio.' (aesthetic flatlay)"],
  watch="Meta restricts 'personal financial hardship' framing — never say 'broke', 'bad with money' or imply you know their financial state. Sell the tool and the ritual, not their failure.",
 ),
 dict(
  name="ADHD / neurodivergent planners & life systems",
  category="Planners & productivity",
  price="$8–$25 standard · $45–$99 full system",
  aov="AOV $25–$45",
  scores=dict(demand=10, meta_fit=10, money_proof=9, margin_ease=9, upsell_ladder=9, speed_to_launch=9, policy_safety=7, low_competition=6, evergreen=9),
  buyers="Adults with late-diagnosed ADHD, students, parents of ADHD kids, women 20–40 who 'tried every planner'",
  why="Identity-driven purchase with an emotional failure story ('normal planners don't work for me'), extremely cheap to make in Canva, and the creative writes itself: low-stimulus pages, flip-throughs, 'brain dump' demos. Underserved vs. generic planners.",
  evidence="A single ADHD digital planner on Etsy reported 50,000+ sales. Gumroad tracker data: top ADHD planner 3,100+ sales at $17 (~$52K) plus a $99 version with 225 sales (~$22K); 'ADHD planner for women / entrepreneurs / college students' flagged as rising with real demand and simpler layouts beating busy ones. Multiple 2026 trend tools list ADHD tools as a rising Etsy category.",
  funnel="$12 low-stimulus planner -> $19 'executive function workbook' bump -> $49 bundle (planner + body-doubling audio + templates) -> $12/mo accountability club",
  hooks=["'If to-do lists have never worked for you, you don't need more discipline.'" ,
         "'This is what my planner looks like on a bad brain day.' (page flip)",
         "'3 planner features that actively make ADHD worse.'"],
  watch="Mental-health adjacency: sell 'tools and structure', never 'treatment', 'cure' or symptom claims. Keep 18+ targeting on anything framed around a condition.",
 ),
 dict(
  name="Wedding & event template suites (Canva/editable)",
  category="Weddings & events",
  price="$12–$50 per suite",
  aov="AOV $35–$80 (multi-item suites)",
  scores=dict(demand=9, meta_fit=9, money_proof=9, margin_ease=9, upsell_ladder=8, speed_to_launch=9, policy_safety=10, low_competition=6, evergreen=8),
  buyers="Newly engaged couples (especially 'wedding on a budget'), plus bridesmaids, mothers-of-the-bride, and vendors who resell them",
  why="Once someone is engaged, every scroll becomes a purchase decision — and Meta is very good at finding 'engaged' behaviour clusters. Instant delivery, zero shipping, price-anchored against $400 stationers. Strong seasonal peak, evergreen base.",
  evidence="Wedding printables: ~1.16M monthly views on top Etsy listings, average price $15.83, with individual invitation templates reporting 13,000+ purchases; wedding stationery repeatedly listed as a single-digit-top Etsy digital category with 5,000+ sales per top listing. Editable Canva templates command 20–40% price premiums over static PDFs.",
  funnel="$19 invitation suite -> $29 'day-of + signage pack' bump -> $69 full stationery bundle -> $149 'wedding ops kit' (timeline, vendor tracker, budget)",
  hooks=["'We printed our whole wedding for £40.' (side-by-side with a stationer quote)",
         "'The 6 wedding printables that stop the panic in the last 2 weeks.'",
         "'POV: your seating chart changes again.' (editable demo screen-record)"],
  watch="No policy landmine. Real risk is design sameness — win with a distinctive art direction (e.g. 'old-money romance', 'châteaucore', dark academia) per 2026 wedding design trends, not another minimal serif suite.",
 ),
 dict(
  name="Kids' educational printables, homeschool & screen-free activity bundles",
  category="Parenting & kids",
  price="$4–$14 single packs · $19–$39 bundles",
  aov="AOV $22–$40 + recurring",
  scores=dict(demand=9, meta_fit=9, money_proof=8, margin_ease=9, upsell_ladder=9, speed_to_launch=8, policy_safety=10, low_competition=7, evergreen=9),
  buyers="Parents of 3–11s, homeschool families, teachers, grandparents, babysitters",
  why="Parents buy repeatedly across an entire year (school terms, holidays, summer slide), the product can be made in Canva in a weekend, and a monthly printable membership turns one-off buyers into MRR. Lowest competition of the big-volume categories because it is unglamorous.",
  evidence="Curriculum-aligned worksheet bundles, party kits and holiday kits are named as the reliable sellers in the printables category, with buyers purchasing repeatedly across the year; holiday worksheets for kids appear on bestseller lists; single-item margins fail but bundles survive ad costs — exactly the structure Meta requires.",
  funnel="$9 themed activity pack -> $19 bundle bump ('term 1 survival pack') -> $27 mega bundle -> $9/mo printable club or $59/yr",
  hooks=["'The 20 minutes before dinner that used to be a meltdown.'" ,
         "'Print this before your next flight.' (pack flip-through, kid using it)",
         "'Summer slide is real — 10 pages a week beats tutoring.'"],
  watch="Strong seasonality (back-to-school, summer, Christmas). Build a calendar of themed drops or revenue will swing 3–4x between months.",
 ),
 dict(
  name="Canva template packs for small businesses & social media kits",
  category="Business & marketing",
  price="$9–$49 per pack · $25–$79 brand kits",
  aov="AOV $30–$60",
  scores=dict(demand=9, meta_fit=9, money_proof=9, margin_ease=9, upsell_ladder=8, speed_to_launch=9, policy_safety=10, low_competition=5, evergreen=8),
  buyers="Etsy/Shopify sellers, coaches, realtors, restaurants, freelancers, podcasters — i.e. people with a budget and a deadline",
  why="The product IS the ad creative, so a single Reel can demo the whole thing in 8 seconds. B2B buyers convert at much higher willingness-to-pay than consumers at the same price point, and kits stack naturally into bundles and memberships.",
  evidence="Named the fastest-growing digital product segment in 2026 trend analysis; a single 'neutral Instagram post templates' pack is documented at 20,000+ sales; average top-100 Etsy listing price across social/business templates sits in the $5–$49 band with 85–95% margins. Niche-specific kits (dog trainers, podcasters, restaurants) flagged as high-demand / low-competition.",
  funnel="$19 niche template pack -> $29 'content calendar + 30 captions' bump -> $59 brand kit -> $19/mo template club",
  hooks=["'Your feed is costing you clients — same offer, 4 different faces.'" ,
         "'Swipe 20 templates that already converted for a [niche] business.'",
         "Screen-record: 'I built this whole week of content in 4 minutes.'"],
  watch="Never put Canva / Instagram / Notion logos or branded UI in ad creative without rights, and never claim affiliation with the platform. Avoid ©-ed assets in your templates — buyers get takedowns and you get refunds.",
 ),
 dict(
  name="Nursing / medical-student study bundles",
  category="Education & exams",
  price="$3–$25 per bundle",
  aov="AOV $20–$35",
  scores=dict(demand=9, meta_fit=8, money_proof=9, margin_ease=10, upsell_ladder=8, speed_to_launch=8, policy_safety=10, low_competition=6, evergreen=8),
  buyers="Nursing students, pre-nursing/NCLEX candidates, med & allied-health students, paramedics — a global audience numbering in the millions that refreshes every intake",
  why="Urgent pain (impending exam, fear of failing a course they paid thousands for), repeat purchase each semester, and huge 'I wish I'd had this' UGC potential in study-content communities where the aesthetic notes Reel is already a native format.",
  evidence="Anatomy & physiology / nursing note listings on Etsy routinely show 500–2,000 reviews with 'high sales volume over the past 6 months' flags, bundles priced $2.88–$25, and mega bundles of 350–1,000+ pages; a single nursing concept-map template listing shows 2,000 reviews. Study guides and workbooks hold $4.99–$9.99+ with classroom/direct sales strongest.",
  funnel="$7 subject cheat sheet -> $12 subject bundle bump -> $29 full-semester bundle (notes + flashcards + worksheets) -> $59 across-semester vault",
  hooks=["'I failed A&P the first time. These 12 pages are what I'd do differently.'",
         "'Your lecturer won't tell you which 40 facts show up every single exam.'",
         "'Study with me: full bundle, page by page.' (ASMR flip-through)"],
  watch="Facts must be accurate — you're selling study material, so errors create refunds and reputational damage. Do not copy content from existing workbooks; commission or write original, and cite your sources. Avoid using exam brands (NCLEX, TEAS) in a way that implies endorsement.",
 ),
 dict(
  name="Reading journals, book trackers & bookish products",
  category="Hobbies & identity",
  price="$3–$15 per journal · $12–$25 deluxe",
  aov="AOV $15–$28",
  scores=dict(demand=8, meta_fit=9, money_proof=8, margin_ease=10, upsell_ladder=7, speed_to_launch=10, policy_safety=10, low_competition=7, evergreen=7),
  buyers="BookTok / Bookstagram readers 18–35, book-club members, 'romance/romantasy reader' identity buyers",
  why="One of the cheapest things to make and the easiest to advertise: the audience self-identifies loudly, the product is aesthetic by nature, and it re-purchases every single January (new year, new tracker). Very low policy risk.",
  evidence="Bookish products described as 'booming thanks to BookTok'; Etsy digital reading journal listings show 3.6k–12.4k sales, printable reading bundles at 12.3k sales, single-tracker templates at 1.8k–3.9k reviews, and dedicated 2026 reading trackers selling for $2.20–$15 with thousands of favourites.",
  funnel="$5 printable tracker -> $9 'review + TBR pack' bump -> $19 digital GoodNotes journal (with stickers) -> $29 'yearly' edition + membership for a book club",
  hooks=["'I read 61 books last year. This is the only tracker I used.'",
         "'Book tracking but it's an iPad journal.' (flip-through)",
         "'Fill a shelf without buying anything new.' (colour-in page)"],
  watch="Low ticket means volume — you need either a big organic BookTok presence or paid traffic at $5 AOV, which almost never works alone. Always bundle; never sell the $3 file as the stand-alone offer.",
 ),
 dict(
  name="Digital iPad / GoodNotes planners & hyperlinked systems",
  category="Planners & productivity",
  price="$6–$25 · $29–$49 deluxe",
  aov="AOV $25–$45",
  scores=dict(demand=9, meta_fit=9, money_proof=8, margin_ease=9, upsell_ladder=8, speed_to_launch=8, policy_safety=10, low_competition=6, evergreen=8),
  buyers="iPad-only students and 20–35s, 'aesthetic note-taking' creators, people who bought an Apple Pencil and use it for nothing else",
  why="Every purchase is peer-visible (it's literally a status object in someone's bag), flip-through Reels are native IG content, and the format supports endless variants — dated/undated, themed, per-profession — so you can keep a creative library fresh without new products.",
  evidence="Etsy listing evidence: a 'Digital Reading Journal for Goodnotes' at 12.4k sales, a classic-paper iPad reading planner at 4.3k sales, a dark-mode iPad reading planner at 3.6k sales, digital planners consistently ranking in the top-3 Etsy digital categories at $8–$25 with ~95% margins.",
  funnel="$12 starter planner -> $19 sticker/dashboard pack bump -> $39 all-in bundle (dated + undated + 5 themes) -> $15/yr updated edition",
  hooks=["'My whole 2026 fits in one file.' (iPad flip-through, satisfying taps)",
         "'Why my planner costs $12 and replaced a $60 one.'",
         "'Undated vs dated — here's which one you actually want.'"],
  watch="Device fragmentation kills conversion: state hyperlinked PDF + GoodNotes/Notability/Android compatibility explicitly or you will drown in support DMs. Annual repurchase depends on shipping a fresh dated edition every Q4.",
 ),
 dict(
  name="AI prompt packs & 'AI for [profession]' playbooks",
  category="Business & marketing",
  price="$9–$29",
  aov="AOV $25–$50",
  scores=dict(demand=9, meta_fit=9, money_proof=7, margin_ease=10, upsell_ladder=8, speed_to_launch=10, policy_safety=9, low_competition=5, evergreen=6),
  buyers="Solopreneurs, realtors, teachers, marketers, recruiters, students — anyone who has tried ChatGPT, got a mediocre answer and blamed themselves",
  why="Cheapest product on this list to make and the most demoable ad on the internet: screen-record the prompt, screen-record the output. Curiosity is the cheapest conversion trigger on Meta. Buyer inflow is still growing, not cannibalised from an existing pool.",
  evidence="AI productivity workflows tracked at roughly +180% YoY with 'role-specific automation guides' up ~210% and low competition; prompt packs/prompt libraries named among the top trending digital product types across Gumroad, Etsy and Whop for 2025–2026, priced $9–$19 for ebook-format collections, 'rising' as an Etsy category.",
  funnel="$9 profession-specific pack -> $19 'workflow + templates' bump -> $39 '450-prompt vault + video walkthrough' -> $19/mo updated prompt club",
  hooks=["'This one prompt replaced my $400/mo copywriter.' (input -> output on screen)",
         "'Stop asking ChatGPT to \"write a post\". Do this instead.'",
         "Role-specific: 'Every realtor should have these 12 prompts saved.'"],
  watch="This is the most crowded fast-money corner: generic prompt lists are already commoditised, and 'make money with AI' angles are the highest-risk ad copy you can write. Win only with a painful niche + a real workflow, never with the prompt volume number.",
 ),
 dict(
  name="Resume / LinkedIn / job-search kits (ATS-ready)",
  category="Careers",
  price="$8–$20 single · $15–$30 bundles",
  aov="AOV $25–$60",
  scores=dict(demand=9, meta_fit=8, money_proof=9, margin_ease=9, upsell_ladder=8, speed_to_launch=10, policy_safety=7, low_competition=6, evergreen=7),
  buyers="Job seekers in a panic — recent grads, laid-off mid-career professionals, career-changers, people re-entering after a break",
  why="Urgency is off the charts and the stakes are financial, so a £12 template to avoid another 6 months of rejection is an easy yes. The outcome is visually provable ('this got 4 interviews in 2 weeks') without touching a restricted category.",
  evidence="Star sellers in the resume category report 4,000–5,000+ purchases; resume templates priced $8–$20 (bundles $15–$30) with ATS-friendly and Google Docs/Word variants named as the top conversion factors; shops running 20–30 listings are reported at $3,000–$6,000/month.",
  funnel="$12 ATS resume template -> $9 cover-letter/LinkedIn bump -> $29 'interview + LinkedIn kit' -> $97 job-search sprint course",
  hooks=["'Your CV isn't bad. The robot can't read it.' (ATS screen demo)",
         "'I sent 40 applications and got nothing. Here's what changed.'",
         "'Rewrite your resume in 20 minutes.' (time-lapse edit)"],
  watch="US advertisers: employment-related campaigns can be pulled into Meta's 'Employment' Special Ad Category, which limits targeting (and job-adjacent creative is the most likely trigger). Keep it product-focused, exclude 18–24 where required, and check current policy before spending.",
 ),
 dict(
  name="Faith-based devotionals, prayer journals & scripture study guides",
  category="Faith & journaling",
  price="$7–$15 single · $19–$39 series",
  aov="AOV $20–$40 + annual series",
  scores=dict(demand=8, meta_fit=8, money_proof=8, margin_ease=10, upsell_ladder=8, speed_to_launch=9, policy_safety=9, low_competition=7, evergreen=9),
  buyers="Practising Christians broadly, plus specific under-served segments: Catholic/liturgical readers, women's ministry groups, small-group leaders, mums of young kids",
  why="Devotionals are bought in series and repeated annually, the audience is enormous and highly engaged, and it's one of the least-advertised big categories — so CPMs tend to be friendlier than business/finance. The product is a PDF that takes days to build.",
  evidence="Devotionals 'sell in series; day-numbered formats do best' with very high repeat-buy ratings; Catholic / liturgical devotionals called out as low-competition in the $9–$15 band; 30-day Christian devotionals listed at $7–$14 with 'very high' repeat purchase; teaching and study guides hold $4.99–$9.99+ with classroom/direct sales strongest.",
  funnel="$9 30-day devotional -> $19 companion journal bump -> $29 full series -> $49/yr devotional + planner subscription",
  hooks=["'Day 1 of 30: read this before your phone.' (peaceful visual, no face)",
         "'A Lent devotional you can actually finish.'",
         "'This is the only journal my small group finished.'"],
  watch="Meta removed detailed religious-interest targeting years ago, so you cannot rely on interest stacks — creative must carry the targeting signal. Never use scripture to make a promise (prosperity framing) and never imply the viewer's faith state.",
 ),
 dict(
  name="GLP-1 companion guides & high-protein meal plans",
  category="Food & health",
  price="$9–$27",
  aov="AOV $27–$55",
  scores=dict(demand=10, meta_fit=8, money_proof=8, margin_ease=9, upsell_ladder=8, speed_to_launch=9, policy_safety=5, low_competition=7, evergreen=6),
  buyers="The millions now on or coming off GLP-1 medications, plus the wider high-protein / 'eat 100g a day' crowd",
  why="One of the fastest-growing consumer behaviour shifts of the decade, and the felt problem is immediate and specific ('what do I actually eat on this, and how do I keep protein up'). Recipe content is the single most watchable ad format there is — food Reels get cheap reach.",
  evidence="Diet-specific cookbooks and hormone/gut-health recipe products are named among the strongest performing ebook categories ($4.99–$14.99), with gut health + sleep optimisation tracked at ~+74% YoY and 'niche cookbooks and diet plans' explicitly flagged as performing extremely well. Note the flip side: generic weight-loss titles are the most crowded shelf in the market.",
  funnel="$14 '50 high-protein meals' -> $9 grocery/serving calculator bump -> $37 8-week meal system -> $19/mo weekly plan",
  hooks=["'On a GLP-1 and can't finish a plate? Eat this instead.' (hands, no body)",
         "'100g of protein without a shake.' (5 quick plates)",
         "'What I meal-prep in 45 minutes for the whole week.'"],
  watch="Highest policy risk on the list. Meta's health & wellness rules restrict weight-management creative, require 18+ targeting, and reject specific outcome or timeframe claims; 'you/your' health framing can trip the personal-attributes rule. Keep it food-first ('recipe pack', 'high-protein planner'), never results-first, and assume slow appeal times.",
 ),
 dict(
  name="Printable wall art, gallery-wall bundles & poster sets",
  category="Home & decor",
  price="$3–$15 single · $19–$49 bundles",
  aov="AOV $18–$35",
  scores=dict(demand=10, meta_fit=8, money_proof=8, margin_ease=9, upsell_ladder=6, speed_to_launch=10, policy_safety=9, low_competition=3, evergreen=8),
  buyers="Renters and first-home decorators on a budget, nursery/new-parent buyers, gift buyers, small businesses decorating a space",
  why="Highest raw volume of any digital category and the easiest 'print it for £2 vs buy it for £80' price-anchor ad in existence. Cheap to make, instantly delivered, and re-buys with the seasonal decor cycle (which is also how you keep revenue alive).",
  evidence="Printables/wall art is consistently the #1 digital-download category by volume on Etsy (digital downloads estimated at $1.2B+/yr, 80–95% margins, $3–$15 typical price), with cohesive gallery-wall sets and bundles named as the winners over single pieces; 2026 design trend shifts are toward maximalist botanical and dark moody abstract replacing the old minimalist look.",
  funnel="$7 print set -> $15 'gallery wall of 6' bump -> $29 seasonal bundle -> $39/yr print club (4 drops a year)",
  hooks=["'£3 versus £80 for the same wall.' (side-by-side)",
         "'Gallery wall in 10 minutes — all 6 prints below.'",
         "'December is coming. Print this set now.' (seasonal drop)"],
  watch="The most saturated category on this list and the easiest to steal/duplicate. Do not enter with generic minimalist quotes — win with a distinctive style, a personal following, or a seasonal drop calendar. Print-on-demand fulfilment (the faster-growing half) also changes the unit economics.",
 ),
 dict(
  name="Personalised kids' storybooks & AI-made personalised gifts",
  category="Parenting & kids",
  price="$15–$39",
  aov="AOV $30–$70 (siblings, gifting)",
  buyers="Parents, grandparents, godparents, aunts/uncles shopping for a birthday",
  why="Emotional, gifting-driven, high perceived value and totally impossible to comparison-shop — 'your child is the hero of this book' converts on sight. Personalisation also justifies a 2–3x price over an equivalent generic product.",
  scores=dict(demand=8, meta_fit=10, money_proof=8, margin_ease=8, upsell_ladder=8, speed_to_launch=7, policy_safety=8, low_competition=7, evergreen=7),
  evidence="Personalised kids' storybooks are documented at 50,000+ sales in creator reports, with 'emotional purchase, great gift idea, high perceived value, scales with automation' named as the reason; AI-assisted personalisation is called out as the fastest-growing Etsy product wave (+240% YoY for AI-assisted digital products).",
  funnel="$19 single personalised book -> $29 sibling version bump -> $49 printed + digital bundle (POD) -> $15 seasonal edition (Christmas/birthday)",
  hooks=["'I made my daughter the main character of her bedtime story.' (page reveal)",
         "'The birthday gift that made a 6-year-old cry.' (parent UGC)",
         "'Type a name, get a book in 60 seconds.' (screen-record demo)"],
  watch="Two real risks: (1) build order-to-delivery automation before you advertise — manual personalisation does not scale past ~20 orders a day and becomes a support nightmare; (2) AI illustration style must be consistent and you must hold commercial rights. Avoid any celebrity or franchise likeness.",
 ),
 dict(
  name="Certification & exam-prep cheat sheets (licence, board, bootcamp)",
  category="Education & exams",
  price="$9–$24",
  aov="AOV $25–$60",
  buyers="Real-estate licence candidates, PMP/IT cert candidates, nursing & teaching boards, coding-interview preppers, apprenticeship exams",
  why="The most economically rational purchase on this list: buyers are already spending $200–$2,000 on the exam, so a $19 set of high-yield notes is noise in their budget. Low competition because most creators don't know these exams exist — and the audience refreshes every exam cycle.",
  scores=dict(demand=8, meta_fit=8, money_proof=7, margin_ease=10, upsell_ladder=8, speed_to_launch=8, policy_safety=9, low_competition=8, evergreen=7),
  evidence="'Certification exam cheat sheets' is named among emerging micro-niches with almost no competition in 2026 niche analysis; exam-prep/study guides hold $9.99–$24.99; the closely related 'role-specific automation guides' niche is tracked at roughly +210% YoY, and careers/job-change content shows ~1.42 momentum (rising).",
  funnel="$12 high-yield cheat sheet -> $19 practice-question pack bump -> $39 full prep bundle -> $79 cohort/mock-exam subscription",
  hooks=["'The 40 facts that show up in almost every [exam] sitting.'",
         "'I passed [exam] in 3 weeks while working full time.'",
         "'Which study resource would I buy again? Only this one.'"],
  watch="You must know the exam. Sloppy accuracy or out-of-date syllabus = refunds and angry reviews, and some boards assert IP over question formats — write original questions, don't scrape. Also note Meta can't reliably target by profession, so the creative has to identify the audience for the algorithm.",
 ),
 dict(
  name="Notion / business 'operating system' templates",
  category="Business & marketing",
  price="$15–$79",
  aov="AOV $40–$90",
  scores=dict(demand=8, meta_fit=7.5, money_proof=8, margin_ease=9, upsell_ladder=9, speed_to_launch=8, policy_safety=9, low_competition=6, evergreen=7),
  buyers="Freelancers, VAs, small agencies, coaches, realtors, content creators — people running a business from a laptop",
  why="Highest ceiling on this list for the upsell ladder: the template can be the entry drug to a $199 'system', a $99/mo community or a $2k done-for-you setup. Buyers in this category are buying time, not a file, so they tolerate higher prices.",
  evidence="In a 200,000-product Gumroad analysis, productivity systems like Notion templates and dashboards were among the most likely to earn (46.3% make money, averaging ~$9,986), with the strongest performers being profession-specific client-management and agency OS templates rather than generic dashboards; Notion templates consistently rank among the best-selling digital products across Gumroad and Etsy.",
  funnel="$29 client-management template -> $39 'onboarding + SOP' bump -> $89 full agency OS -> $199 course or $99/mo community",
  hooks=["'My whole agency runs on one page.' (screen-record, 20 seconds)",
         "'If you're still tracking clients in your notes app, watch this.'",
         "'Duplicated this 240 times. Here's what's inside.'"],
  watch="Notion's own free-template ecosystem and YouTube tutorials cap how much you can charge for an obvious dashboard. Win by being profession-specific and by shipping setup video + a filled-in example — that packaging is what moves a bare file into a much higher price bracket.",
 ),
 dict(
  name="Crochet / knitting patterns & SVG craft files",
  category="Crafts & hobbies",
  price="$3–$12 patterns · $2–$8 SVG",
  aov="AOV $15–$30 (bundles)",
  scores=dict(demand=8, meta_fit=7, money_proof=8, margin_ease=10, upsell_ladder=7, speed_to_launch=9, policy_safety=10, low_competition=5, evergreen=9),
  buyers="Crocheters and knitters (a very large, very online, very repeat-purchase hobby base), Cricut/Silhouette crafters, small craft sellers",
  why="Almost pure passive income: makers buy patterns repeatedly, month after month, and crafters are extremely easy to find on Meta. The winning play isn't one bestseller — it's a 200-listing catalogue, which is also exactly what the algorithm rewards.",
  evidence="Digital patterns (crochet/knitting/sewing) hold $3–$25 with low competition and medium repeat buying; SVG cut files show 200–800 sales/month at $2–$8 with very high repeat purchase; crochet & knitting patterns appear on Etsy bestseller lists year-round with strong evergreen demand.",
  funnel="$5 pattern -> $15 5-pattern bundle bump -> $29 seasonal pattern club -> $8/mo membership (monthly pattern drop)",
  hooks=["'One skein. One evening. This is the whole pattern.' (timelapse make)",
         "'The mistake every beginner makes on row 3.'",
         "'Cricut users: 20 files you'll use all December.'"],
  watch="Price floor is brutal — a $3 pattern cannot carry cold Meta traffic on its own, and Etsy now floods these categories with AI-generated pattern art. Enter as a bundle/membership play or as an organic-first channel, not a paid-traffic-only product.",
 ),
 dict(
  name="Perimenopause / hormone-health trackers & doctor-visit kits",
  category="Women's health",
  price="$9–$25",
  aov="AOV $25–$60",
  scores=dict(demand=8.5, meta_fit=8, money_proof=7, margin_ease=9, upsell_ladder=8, speed_to_launch=8, policy_safety=6, low_competition=9, evergreen=8),
  buyers="Women 38–55 navigating symptoms with no clear medical pathway, and their partners/adult children buying for them",
  why="Textbook underserved demand: an enormous, affluent, ignored audience sitting between 'free app' and '$300/month functional-medicine programme'. A structured symptom tracker + doctor-visit prep sheet is a genuinely novel product, not another planner reskin.",
  evidence="Analysts flag 'desperate' demand with nothing structured existing between free apps and expensive clinics, specifically naming perimenopause symptom trackers with doctor-visit prep; perimenopause is also listed as an under-served ebook topic for women 38–50 with willingness to pay for practical guidance; women's health is repeatedly identified as a category gap between small-platform coverage and Amazon-scale demand.",
  funnel="$14 symptom tracker + doctor prep -> $19 'what to ask your GP' bump -> $39 8-week protocol bundle -> $19/mo community or $97 group course",
  hooks=["'Go to your appointment with this, not a vague description.'",
         "'I tracked this for 90 days. The pattern was obvious.' (tracker pages)",
         "'The 12 questions that got me taken seriously.'"],
  watch="Health category rules apply: 18+ targeting, no symptom or cure claims, no 'do you struggle with…' second-person health framing. Sell organisation and preparation, not diagnosis or treatment — and get a clinician to review content before you sell it.",
 ),
 dict(
  name="Faceless-instagram / theme-page growth guides + MRR-PLR resell packs",
  category="Make money online",
  price="$7–$41",
  aov="AOV $30–$90",
  scores=dict(demand=8, meta_fit=9, money_proof=8, margin_ease=9, upsell_ladder=7, speed_to_launch=9, policy_safety=5, low_competition=4, evergreen=5),
  buyers="People who want a side income and don't want to show their face — a self-selecting group that is already being advertised to on Instagram",
  why="This is the category that most aggressively advertises on Meta, which is both the reason it works and the reason to be careful: the buyer is the same person the ad targets, the price point is tiny, and the pitch is trivially testable.",
  evidence="Faceless marketing guides with MRR/PLR rights are sold at $4–$41 across Etsy and independent stores, promoted with exactly the 'buy it, learn it, rebrand it, resell it for 100% profit' positioning; guides and planners with resale rights are listed among Etsy's top-selling digital products in 2026. Caveat: side-hustle/online-income reader trust is flagged as low and the niche shows cooling momentum (0.73).",
  funnel="$7 ebook -> $17 'resell rights' bump -> $37 bundle -> $97/mo mentorship or community",
  hooks=["'I built this page without ever showing my face.'",
         "'You can resell this as your own — here's how it works.'",
         "'3 reasons your theme page isn't converting (not the niche).'"],
  watch="The dirtiest corner of this list. Income-claim ads get rejected and attract complaints; MRR products are frequently rebranded copies with no real IP; refund and chargeback rates run high; and the honest failure rate is most people who buy. If you play here, sell a real skill with real proof, disclose what resale rights actually allow, and expect to work for the sale rather than coasting on a low ticket.",
 ),
 dict(
  name="Manifestation, shadow-work & spiritual journals",
  category="Faith & journaling",
  price="$7–$18",
  aov="AOV $18–$35",
  scores=dict(demand=8, meta_fit=8, money_proof=7, margin_ease=10, upsell_ladder=7, speed_to_launch=9, policy_safety=6, low_competition=4, evergreen=7),
  buyers="Women 18–40 into manifestation, journaling, 'soft life' and aesthetic spirituality, plus gift buyers",
  why="Aesthetic, emotional, identity-driven purchase with near-zero production cost and one of the highest repeat-purchase rates in the journal category. Reels creative is cheap: pages, sunlight, a pen.",
  evidence="Manifestation & shadow-work journals are rated 'very high' repeat buying on Etsy at $7–$12; guided journals are named among the strongest Etsy ebook/journal niches; mental-health-adjacent journaling workbooks ($9–$24) are flagged as one of the fastest-growing niches of the last 18 months.",
  funnel="$9 journal -> $15 prompt-cards/sticker bump -> $29 'complete ritual kit' -> $49/yr revised edition",
  hooks=["'Day 1 of 21. Write this before you check your phone.'",
         "'Shadow work prompts that aren't cringe.'",
         "'The journal I've refilled 4 times.'"],
  watch="Two ceilings: saturation is severe (this is the most-cloned aesthetic niche on Etsy) and Meta's personal-attributes rule bites when copy implies the viewer's psychological or spiritual state ('are you stuck in a scarcity mindset?'). Sell the ritual, not the reader's wounds.",
 ),
]

# ---- score & rank -----------------------------------------------------------
for p in P:
    p["total"] = round(sum(p["scores"][k] * w for k, w, _ in FACTORS), 2)

P.sort(key=lambda x: (-x["total"], -x["scores"]["money_proof"], -x["scores"]["meta_fit"]))

